fjs.i18n = {
	'en':{
		/****************ME LABELS******************/
		avatar_hover_menu: '写真ホバーメニュー遅延',
		enable_box: 'ボックス有効化',
		reset_app_menu_order: 'アプリメニューオーダーをリセット',
		sound_quality: '音質設定',
		web_phone_state: 'Web phone state',
		registered: 'registered',
		microphone: 'microphone',
		me: 'me',
		all: 'all',
		name: 'name',
		extension: 'extension',
		call_status: 'Call Status',
		hud_status: 'HUD Status',
		available: 'available',
		away:'away',
		busy:'busy',
		favorites: 'favorites',
		external: 'external',
		group: 'group',
		my_department: 'My Department',
		my_department_collaborate: '部門のメンバ',
		all_other_departments: '全ての他部門',
		other_departments: '他部門',
		my_teams: 'チーム',
		teams_managed_by_me:'管理チーム',
		shared:'シェアチーム',
		member_of_teams: '私はチームメンバです',
		others:'その他',
		teams_visible_to_everyone:'他に見えるチーム',
		//call_status:'呼状態',
		members:'メンバー',
		custom_status:'Custom Status',
		location: 'location',
		carrier: '通信事業者',
		hud_mobile: 'HUDモバイルソフトフォン',
		hud_web:'HUDWebソフトフォン',
		office:'オフィス',
		chat_status: 'CHAT STATUS',
		place_a_call: 'Place a call',
		phone_number:'電話番号',
		cuurent_call:'通話時間',
		transfer:'transfer',
		conf_room:'Conf Room',
		park:	'Park',
        hold:	'Hold',
        REC:	'REC',
        move:	'Move',
        end:	'End',
        accept: 'Accept',
        decline:'Decline',
        talk:'talk',
        recent_calls:'Recent Calls',
  		date:'Date',
  		time:'Time',
    	today:'Today' , 
    	yesterday:'Yesterday',
    	AM: 'am',
　  		PM:	'pm',
  		from:	'from',
    	you:	'you',
  		to:	'to',
   		duration:	'Duration',
		preferences:	'Preferences',
    	general:	'General',
　　　	  language:	'Language',
        autoclear_search:	'Autoclear search',
        autoclear_after: 'Autoclear after ',
        seconds: '秒',
        avatar_hover_menu_delay:	'Avatar hover menu delay',
        enable_box:	'Enable Box',
        reset_app_menu_order:  'Reset App Menu Order',
		sound_quality_setting: 	'音質設定',
		speaker: 'speaker'　,　　	
      	echo:	'Echo',
      	device:'Device',
      	select_device_to_use:'Select Device to use',
      	wave_mapper:'ウェブ・マッパー',
      	input_devices:	'Input Devices',
        output_devices:	'Output Devices',
        ring_devices:	'リングデバイス',
		weblauncher:	'ウェブランチャー',
		general_settings:'一般設定',
        weblauncher_profile:'ウェッブランチャープロファイル',
　　　 	launch_page_when_answered:'着信応答時ウェブ表示',
		outbound_calls:'アウトバンドコール',
		outbound_calls_settings:'アウトバンド設定',
		launch_page_during_calls: '発信時ウェブ表示',
		launch_page_after_hang_up:'切断時ウェブ表示',
		silent:'サイレント',
		auto_launch:'自動表示',
		inbound_calls:'インバンドコール',
		inbound_call_settings:'インバンドコール設定',
		web_launcher_variables:'ウェブランチャーパラメータ',
		web_launcher_var_desc:'ウェブランチャーパラメータ記述',
		variables:'パラメータ',
		description:'パラメータ説明',
		inbound:'インバンド',
		outbound:'アウトバンド',
		queues:'またはキュー着信',
		wl_var_desc_username_accounts:'認証を要求するアカウントのユーザネーム',
		wl_var_desc_duration:'通話の経過時間（秒）',
		wl_var_desc_name_of_party:'接続先番号',
		wl_var_desc_call_type:'呼種別',
		wl_var_desc_your_ext:'内線番号',
		wl_var_desc_name_of_your_party:'接続先番号',
		wl_var_desc_your_password:'認証を要求するアカウントのパスワード',
		wl_var_desc_caller_number:'%%caller_number%%文字列の削除された部分',
		queues:'キュー',
		waiting:'待ち合わせ中',
		calls:'calls',
		avg_wait:'平均待ち時間',
		avg_talk:'平均通話時間',
		minutes:'分',
		abandoned:'途中放棄',
		avatar_upload: '写真 アップロード',
    	first_name:	'名',
     	last_name:	'姓',
    	display_name:'HUDweb表示名称',
　      email: 'eメール',
   		mobile:	'携帯番号',
　　    voicemail:	'ボイスメールアドレス',
　　    business_phone:	'ビジネス番号',
　　    extension:	'内線番号',
       IMS:	'IMS',
       JID:	'JID',
　　　  my_department:'所属部門',
	   alerts: 'アラート',
	   configure_desktop_alerts: 'デスクトップアラート設定',
	   show_alerts:	'アラート表示',
   	   show_status_when_busy:'ビジー時アラート表示',
   	   show_when_app_in_focus:'アプリケーションフォーカス時表示',
   	   voicemail_alerts:'ボイスメールアラート',
   	   configure_desktop_alerts:'デスクトップアラート設定',
   	   show_when_new_voicemail: '新着のボイスメールを表示',
   	   call_alerts: '通話アラート',
　     configure_call_desktop_alerts:'通話デスクトップアラート設定',
   	   type:'タイプ',
       incoming_calls:	'発信通話',
       outbound_calls:	'着信通話',
	   display_for:	'表示条件',
　　　　all_my_calls:	'全ての通話を表示する',
       only_for_known_numbers:	'既知の番号のみ表示する',
       never_display:	'表示しない',
       entire_call_recommended: '常に表示',
       while_phone_is_ringing:' 呼び出し中表示',
       queue_alerts: 'キューアラート',
       configure_queue_not_and_desktop_alerts: 'キュー通知とデスクトップアラート設定',
       select_all: '全て選択',
       long_waiting_call: '長時間待ち合わせ',
       notifications: '通知',
       desktop_alerts: 'デスクトップアラート',
       abandoned_calls: '途中放棄',
       cp: 'ＣＰ画面',
       HOME: 'HOME',
       user_control_panel:'ユーザコントロールパネル',
       features: '電話を使う多くの機能',
       ACD: 'ACD',
       auto_call_distro:'自動通話振り分け',
       about: 'Fonality情報',
       fonality_web_client:'フォナリティWEBクライアント',
       fon_cloud_service:'フォナリティクラウドサービス',
       custom_message:'Custom Message',
       current_call:'Current Call',
		interface_word:'interface',
		application_tuning:'Application tuning',
		sound_quality:'Sound Quality',
        sound_settings:'Sound Settings',
        sounds: 'Sounds',
        enable_chat_sound:'Enable chat sound',
        on_message_received:'On message received',
        on_sent_message:'On sent message',
       sound_settings_general_desc:'Sound settings for chat and notifications',
       call_preferences:'Call preferences',
       call_log_size:'Call log size',
       busy_ring_back:'Busy ring back',
       auto_away: 'Auto Away',
       auto_away_settings_desc: 'Auto away settings',
       auto_away_after: 'Auto away after',
       enable_auto_away:'Enable Auto away',
		
	},

	/*****Japanese Language******/
	'jp':{

		/****************ME LABELS******************/
		avatar_hover_menu: '写真ホバーメニュー遅延',
		enable_box: 'ボックス有効化',
		reset_app_menu_order: 'アプリメニューオーダーをリセット',
		sound_quality: '音質設定',
		web_phone_state: 'ウェブフォン状態',
		registered: '登録ずみ',
		microphone: 'マイクロホン',
		custom_message:'カスタムメッセージ',
		interface_word:'インタフェース',
		application_tuning:'アプリケーションのチューニング',
		me: '自席',
		all: '全席',
		name: '名称',
		extension: '内線',
		call_status: '端末状態',
		hud_status: 'HUD 状態',
		available: 'オンライン/オフライン',
		away:'離席',
		busy:'取り込み中',
		favorites: 'よく使う端末',
		external: '外部コンタクト',
		group: 'グループ',
		my_department: '部門',
		my_department_collaborate: '部門のメンバ',
		all_other_departments: '全ての他部門',
		other_departments: '他部門',
		my_teams: 'チーム',
		teams_managed_by_me:'管理チーム',
		shared:'シェアチーム',
		member_of_teams: '私はチームメンバです',
		others:'その他',
		teams_visible_to_everyone:'他に見えるチーム',
		//call_status:'呼状態',
		members:'メンバー',
		custom_status:'マイメッセージ',
		location: 'マイメッセージ',
		carrier: '通信事業者',
		hud_mobile: 'HUDモバイルソフトフォン',
		hud_web:'HUDWebソフトフォン',
		office:'オフィス',
		chat_status: 'チャット状態',
		place_a_call: '発信',
		phone_number:'電話番号',
		cuurent_call:'通話時間',
		transfer:'転送',
		conf_room:'電話会議',
		park:	'パーク',
        hold:	'保留',
        REC:	'録音',
        move:	'ロケーション移動',
        end:	'終了',
        accept: '許容',
        decline:'拒否',
        talk:'　通話中',
        recent_calls:'最近の通話',
  		date:'日',
  		time:'時',
    	today:'今日' , 
    	yesterday:'昨日',
    	AM: '午前',
　  		PM:	'午後',
  		from:	'発信元',
    	you:	'あなた',
  		to:	'通話相手',
   		duration:	'通話時間',
		Preferences:	'HUDWeb情報',
    	general:	'一般',
　　　	language:	'言語',
        autoclear_search:	'自動クリア検索',
        autoclear_after:'自動クリア検索',
        seconds: '秒',
        avatar_hover_menu_delay:	'写真ホバーメニュー遅延',
        enable_box:	'ボックス有効化',
        reset_app_menu_order:  'アプリメニューオーダーをリセット',
        sound_quality:'音質設定',
        sound_settings:'音の設定',
		sound_quality_setting: 	'音質設定',
		speaker: 'スピーカー'　,　　	
      	echo:	'エコー',
      	device:'端末',
      	select_device_to_use:'利用デバイス設定',
      	wave_mapper:'ウェブ・マッパー',
      	input_devices:	'入力デバイス',
        output_devices:	'出力デバイス',
        ring_devices:	'リングデバイス',
		weblauncher:	'ウェブランチャー',
		general_settings:'一般設定',
        weblauncher_profile:'ウェッブランチャープロファイル',
　　　 	launch_page_when_answered:'着信応答時ウェブ表示',
		outbound_calls:'アウトバンドコール',
		outbound_calls_settings:'アウトバンド設定',
		launch_page_during_calls: '発信時ウェブ表示',
		launch_page_after_hang_up:'切断時ウェブ表示',
		silent:'サイレント',
		auto_launch:'自動表示',
		inbound_calls:'インバンドコール',
		inbound_call_settings:'インバンドコール設定',
		web_launcher_variables:'ウェブランチャーパラメータ',
		web_launcher_var_desc:'ウェブランチャーパラメータ記述',
		variables:'パラメータ',
		description:'パラメータ説明',
		inbound:'インバンド',
		outbound:'アウトバンド',
		queues:'またはキュー着信',
		wl_var_desc_username_accounts:'認証を要求するアカウントのユーザネーム',
		wl_var_desc_duration:'通話の経過時間（秒）',
		wl_var_desc_name_of_party:'接続先番号',
		wl_var_desc_call_type:'呼種別',
		wl_var_desc_your_ext:'内線番号',
		wl_var_desc_name_of_your_party:'接続先番号',
		wl_var_desc_your_password:'認証を要求するアカウントのパスワード',
		wl_var_desc_caller_number:'%%caller_number%%文字列の削除された部分',
		queues:'キュー',
		waiting:'待ち合わせ中',
		calls:'呼',
		avg_wait:'平均待ち時間',
		avg_talk:'平均通話時間',
		minutes:'分',
		abandoned:'途中放棄',
		avatar_upload: '写真 アップロード',
    	first_name:	'名',
     	last_name:	'姓',
    	display_name:'HUDweb表示名称',
　      email: 'eメール',
   		mobile:	'携帯番号',
　　    voicemail:	'ボイスメールアドレス',
　　    business_phone:	'ビジネス番号',
　　    extension:	'内線番号',
       IMS:	'IMS',
       JID:	'JID',
　　　  my_department:'所属部門',
	   alerts: 'アラート',
	   configure_desktop_alerts: 'デスクトップアラート設定',
	   show_alerts:	'アラート表示',
   	   show_status_when_busy:'ビジー時アラート表示',
   	   show_when_app_in_focus:'アプリケーションフォーカス時表示',
   	   voicemail_alerts:'ボイスメールアラート',
   	   configure_desktop_alerts:'デスクトップアラート設定',
   	   show_when_new_voicemail: '新着のボイスメールを表示',
   	   call_alerts: '通話アラート',
　     configure_call_desktop_alerts:'通話デスクトップアラート設定',
   	   type:'タイプ',
       incoming_calls:	'発信通話',
       outbound_calls:	'着信通話',
	   display_for:	'表示条件',
　　　　all_my_calls:	'全ての通話を表示する',
       only_for_known_numbers:	'既知の番号のみ表示する',
       never_display:	'表示しない',
       entire_call_recommended: '常に表示',
       while_phone_is_ringing:' 呼び出し中表示',
       queue_alerts: 'キューアラート',
       configure_queue_not_and_desktop_alerts: 'キュー通知とデスクトップアラート設定',
       select_all: '全て選択',
       long_waiting_call: '長時間待ち合わせ',
       notifications: '通知',
       desktop_alerts: 'デスクトップアラート',
       abandoned_calls: '途中放棄',
       cp: 'ＣＰ画面',
       HOME: 'HOME',
       user_control_panel:'ユーザコントロールパネル',
       features: '電話を使う多くの機能',
       ACD: 'ACD',
       auto_call_distro:'自動通話振り分け',
       about: 'Fonality情報',
       fonality_web_client:'フォナリティWEBクライアント',
       fon_cloud_service:'フォナリティクラウドサービス',
       current_call:'通話通の呼',
       sounds: '音',
       sound_settings_general_desc:'チャットと通知のサウンド設定',
       enable_chat_sound:'チャットサウンドをオンにする',
       on_message_received:'メッセージ受信時',
       on_sent_message:'メッセージ送信時',
        call_preferences:'通話の設定',
       call_log_size:'通話ログファイルサイズ',
       busy_ring_back:'ビジーリングバックトーン',
       auto_away: '自動離席',
       auto_away_settings_desc: '自動離席設定',
       auto_away_after: '自動離席後',
       enable_auto_away:'自動離席を有効',
	}
}