fjs.i18n = {
	'us':{
    /******global*****/
    contacts:'Contacts',
    Groups:'Groups',
    group: 'group',
    Conferences:'Conferences',
    queues:'Queues',
    member:'member(s)',
    phone:'Phone',
    date:'Date',
    type:'Type',
    Call:'Call',
    chat:'Chat',
    recordings:'Recordings',
    cancel:'cancel',
    select:'Select',
    clear_selection:'Clear Selection',
    
	/****************ME LABELS******************/
	avatar_hover_menu: 'å†™çœŸãƒ›ãƒ�ãƒ¼ãƒ¡ãƒ‹ãƒ¥ãƒ¼é�…å»¶',
	enable_box: 'ãƒœãƒƒã‚¯ã‚¹æœ‰åŠ¹åŒ–',
	reset_app_menu_order: 'ã‚¢ãƒ—ãƒªãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚ªãƒ¼ãƒ€ãƒ¼ã‚’ãƒªã‚»ãƒƒãƒˆ',
	sound_quality: 'éŸ³è³ªè¨­å®š',
	web_phone_state: 'Web phone state',
	registered: 'registered',
	microphone: 'microphone',
	me: 'me',
	all: 'all',
	name: 'name',
	extension: 'extension',
	call_status: 'Call Status',
	hud_status: 'HUD Status',
	available: 'available',
	away:'away',
	busy:'busy',
	favorites: 'favorites',
	external: 'external',
    team: 'Team',
	public_team: 'Public Team',
    my_department: 'My Department',
	my_department_collaborate: 'Collaborate with your colleagues',
	all_other_departments: 'All Other Departments',
	other_departments: 'Other departments',
	my_teams: 'My Teams',
	teams_managed_by_me:'Teams managed by me',
	shared:'Shared',
	member_of_teams: "I'm a member of these teams",
	others:'Others',
	teams_visible_to_everyone:'Teams visible to everyone',
	//call_status:'å‘¼çŠ¶æ…‹',
	members:'Members',
	custom_status:'Custom Status',
	location: 'location',
	carrier: 'é€šä¿¡äº‹æ¥­è€…',
	hud_mobile: 'HUDãƒ¢ãƒ�ã‚¤ãƒ«ã‚½ãƒ•ãƒˆãƒ•ã‚©ãƒ³',
	hud_web:'HUDWebã‚½ãƒ•ãƒˆãƒ•ã‚©ãƒ³',
	office:'ã‚ªãƒ•ã‚£ã‚¹',
	chat_status: 'CHAT STATUS',
	place_a_call: 'Place a call',
	phone_number:'Phone number',
	cuurent_call:'é€šè©±æ™‚é–“',
	transfer:'transfer',
	conf_room:'Conf Room',
	park:	'Park',
    hold:	'Hold',
    REC:	'REC',
    move:	'Move',
    end:	'End',
    accept: 'Accept',
    decline:'Decline',
    talk:'talk',
    recent_calls:'Recent Calls',
	time:'Time',
	today:'Today' , 
	yesterday:'Yesterday',
	AM: 'am',
	PM:	'pm',
	from:	'from',
	you:	'you',
	to:	'to',
	duration:	'Duration',
	preferences:	'Preferences',
	general:	'General',
    language:	'Language',
    autoclear_search:	'Autoclear search',
    autoclear_after: 'Autoclear after ',
    seconds: 'ç§’',
    avatar_hover_menu_delay:	'Avatar hover menu delay',
    enable_box:	'Enable Box',
    reset_app_menu_order:  'Reset App Menu Order',
	sound_quality_setting: 	'éŸ³è³ªè¨­å®š',
	speaker: 'speaker',	
  	echo:	'Echo',
  	device:'Device',
  	select_device_to_use:'Select Device to use',
  	wave_mapper:'ã‚¦ã‚§ãƒ–ãƒ»ãƒžãƒƒãƒ‘ãƒ¼',
  	input_devices:	'Input Devices',
    output_devices:	'Output Devices',
    ring_devices:	'Ring Devices',
	weblauncher:	'Web Launcher',
	general_settings:'General settings',
    weblauncher_profile:'ã‚¦ã‚§ãƒƒãƒ–ãƒ©ãƒ³ãƒ�ãƒ£ãƒ¼ãƒ—ãƒ­ãƒ•ã‚¡ã‚¤ãƒ«',
    launch_page_when_answered:'Launch web page only when the call is answered',
	outbound_calls:'Outbound Calls',
	outbound_calls_settings:'Outbound calls settings',
	launch_page_during_calls: 'ç™ºä¿¡æ™‚ã‚¦ã‚§ãƒ–è¡¨ç¤º',
	launch_page_after_hang_up:'åˆ‡æ–­æ™‚ã‚¦ã‚§ãƒ–è¡¨ç¤º',
	silent:'Silent',
	auto_launch:'Auto Launch',
	inbound_calls:'Inbound Calls',
	inbound_call_settings:'inbound call settings',
	web_launcher_variables:'Web Launcher Variables',
	web_launcher_var_desc:'Web launcher variables description',
	variables:'Variable',
	description:'Description',
	inbound:'Inbound',
	outbound:'OutBound',
	wl_var_desc_username_accounts:'èª�è¨¼ã‚’è¦�æ±‚ã�™ã‚‹ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã�®ãƒ¦ãƒ¼ã‚¶ãƒ�ãƒ¼ãƒ ',
	wl_var_desc_duration:'é€šè©±ã�®çµŒé�Žæ™‚é–“ï¼ˆç§’ï¼‰',
	wl_var_desc_name_of_party:'æŽ¥ç¶šå…ˆç•ªå�·',
	wl_var_desc_call_type:'å‘¼ç¨®åˆ¥',
	wl_var_desc_your_ext:'å†…ç·šç•ªå�·',
	wl_var_desc_name_of_your_party:'æŽ¥ç¶šå…ˆç•ªå�·',
	wl_var_desc_your_password:'èª�è¨¼ã‚’è¦�æ±‚ã�™ã‚‹ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã�®ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰',
	wl_var_desc_caller_number:'%%caller_number%%æ–‡å­—åˆ—ã�®å‰Šé™¤ã�•ã‚Œã�Ÿéƒ¨åˆ†',
	waiting:'Waiting',
	calls:'calls',
	avg_wait:'Avg Wait',
	avg_talk:'Avg Talk',
    aban: 'Aband',
	minutes:'minutes',
	abandoned:'Abandoned',
	avatar_upload: 'å†™çœŸ ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰',
	first_name:	'First name',
 	last_name:	'Last Name',
	display_name:'Display Name',
    email: 'E-Mail',
	mobile:	'Mobile',
    voicemail:	'Voicemail',
    business_phone:	'Business phone',
    IMS:	'IMS',
    JID:	'JID',
    alerts: 'Alerts',
    configure_desktop_alerts: 'Configure Desktop Alerts',
    show_alerts:	'Show alerts',
    show_status_when_busy:' Show when status is "Busy"',
    show_when_app_in_focus:'Show when app is in focus',
    voicemail_alerts:'VOICEMAIL ALERTS',
    configure_desktop_alerts:'Configure voicemail desktop alerts',
    show_when_new_voicemail: 'Show when new voicemail arrives',
    call_alerts: 'Call Alerts',
    configure_call_desktop_alerts:'Configure call desktop alerts',
    incoming_calls:	'Incoming Calls',
    outbound_calls:	'Outgoing Calls',
    display_for:	'Display for',
    all_my_calls:	'All my calls',
    only_for_known_numbers:	'Only for known numbers',
    never_display:	'Never display',
    entire_call_recommended: 'Entire Call (recommended)',
    while_phone_is_ringing:' While phone is ringing',
    queue_alerts: 'Queue Alerts',
    configure_queue_not_and_desktop_alerts: 'Configure queue notifications and desktop alerts',
    select_all: 'Select All',
    long_waiting_call: 'Long Waiting Calls',
    notifications: 'Notifications',
    desktop_alerts: 'Desktop Alerts',
    abandoned_calls: 'Abandoned Call',
    cp: 'CP',
    HOME: 'HOME',
    user_control_panel:'User Control Panel',
    features: 'Features (FMFM etc.)',
    features_desc_sum:'Many functions can be used via your phone',
    ACD: 'ACD',
    auto_call_distro:'The Automatic Call Distrbution.',
    about: 'About',
    fonality_web_client:'Fonality Web Client',
    fon_cloud_service:'Fonality Cloud Service',
    custom_message:'Custom Message',
    current_call:'Current Call',
	interface_word:'interface',
	application_tuning:'Application tuning',
	sound_quality:'Sound Quality',
    sound_settings:'Sound Settings',
    sounds: 'Sounds',
    enable_chat_sound:'Enable chat sound',
    on_message_received:'On message received',
    on_sent_message:'On sent message',
    sound_settings_general_desc:'Sound settings for chat and notifications',
    call_preferences:'Call preferences',
    call_log_size:'Call log size',
    busy_ring_back:'Busy ring back',
    auto_away: 'Auto Away',
    auto_away_settings_desc: 'Auto away settings',
    auto_away_after: 'Auto away after',
    enable_auto_away:'Enable Auto away',
    dashboard:'DASHBOARD',
    dashboard_setting: 'Dashboard settings',
    use_column_layout: 'Use column layout',
    web_launcher: 'Web Launcher',
    web_launcher_profile:'Web Launcher Profile',
    web_launcher_on_new_calls:'Launch the web page below during new calls',
    web_launcher_on_hang_ups:'Launcher the web page below after call hangs up',
    queue_summary_stats:'Queue summary stats',
    highlight_threshold:'Highlight threshold. Set to 0 if stat is never highlighted.',
    calls:'Calls',
    waiting:'Waiting',
    my_account:'My account',
    my_account_info:'My account information',
    login:'Login',
    Server:'Server',
    my_personal_info: 'My Personal Information',
    my_personal_info_desc: 'This information is visible to your contacts list',
    avatar:'Avatar',
    reset_alert_position:'Reset Alert Position',
    fon_pbx_control_server: 'Fonality PBX Control Server',
    fon_pbx_server:'Fonality PBX Server',
    fon_plugin:'Fonality Plugin',
    version:'Version',
    fdp_version:'FDP Version',
    hud_server_version:'HUDserver Version',
    fon_core_version:'FONcore Version',
    /***TOP NAVIGATION LABELS **/
    me:'Me',
    call_and_recordings:'Calls & Recordings',
    conferencing:'Conferencing',
    callcenter:'Call Center',
    zoom:'Video Collaboration',
    search:'Search',
    box:'Box',

    /***Left Bar Navigation **/
    all:'All',
    recent:'Recent',
    new_word:'New',
    loading:'Loading',
    offline:'offline',
    events:'events',
    new_call:'New Call',
    add_someone:'Add Someone',

  /**** ZOOM ****/
  video_collaboration_summary: "You are licensed to use Fonality's Video Collaboration. With this feature, you can hold live video meetings with others inside, or outside, your company. You can even share screens. To get started, simply join or start a meeting below.",
  join_summary:"To join a video collaboration session started by someone else, enter the Meeting ID below, and click the 'Join Now' button.",
  create_summary:"To create a new video collaboration session, select the type of video session you'd like to start below, and optionally select people from HUD that you'd wish to invite - they will be sent a link in HUD automatically.",
  start_screen_share_only:"Start with Screen Share Only",
  start_with_video:"Start with Video",
  join_now:'Join Now',
  join:'Join',
  create:'Create',
  link:'Link',
  meeting_id:'Meeting ID',
  zoom_created:'Video Meeting has been created',
  link_to_join:'link to join:',
  to:'to',
  from:'from',
  /*****Search WIdget ******/
  type_for_results:'Type or speak for results',
  search_to_start_convo:'Search to Start Conversation',
  type_subject_name:'Type or speak name of contact, team, queue, or conference room...',

  /***** Call Recordings *****/
  call_log_tab:'Call Log',
  voicemail_tab:'Voicemails',
  my_recordings_tab:'My Recordings',
  no_transcriptions:'no transcription available',

  action:'Actions',
  mark_all_incoming_vm_read:'Mark all incoming voicemails as read',
  mark_all_incoming_vm_unread:'Mark all incoming voicemails as unread',
  delete_all_incoming_read:'Delete all read incoming voicemails', 

  sort_newest_first:'Newest First',
  sort_alphabetically:'Alphabetically',
  sort_oldest_first:'Oldest First',
  sort_read_status:'Read Status',

  /*****Conferences*******/
  conferencing:'Conferencing',
  conference_member:'Conference Members',
  my_rooms:'My Rooms',
  all_rooms:'All Rooms',
  find_free_room:'Find Free Room & Join',
  sort_room:'Sort By Room Number',
  sort_room_by_location:'Sort By Location',
  sort_by_activity:'Sort By Activity',
  sort_by_room_number:'Sort By Room number',
  conf_summary_my_rooms:'These are the rooms that you have advanced permissions to use, such as adding or removing other users.',
  conf_summary_all_rooms:'You may have limited control over some rooms in this list, such as adding or removing other users',
  free_room:'Free room',
  occupied:'Occupied',
  talking:'talking',
  rooms:'Rooms',
  room:'Room',
  total:'Total',
  you_are_on_call:'you are on a call',
  
  not_a_member_of_conference:'You are not a member of this conference',
  join_to_chat:'Join conference call to use chat.',
  only_see_messages_during_chat:'You can see only messages sent during conference call.',

  leave:'Leave',
  /***Conversation***/
  department:'Department',
  member_of_department:'Contact is a member of this department',
  our_teams:'Our Teams',
  both_in_these_teams:'We are both both in these teams',

  /*****QUEUES******/
  login_all:'Login All',
  logout_all:'Logout All',
  logged_in:'Logged In',
  logged_out:'Logged Out',
  logout:'Log Out',
  active:'Active',
  queue_name:'Queue Name',
  my_queue:'My Queue',
  all_queues:'All Queues',
  my_status:'My Status',
  agents:'Agents',
  queue_sort_calls_wait:'Calls Waiting',
  queue_sort_avg_wait_time:'Average wait time(ESA)',
  queue_sort_avg_talk_time:'Average talk time',
  queue_sort_total_calls:"Total calls (since last reset)",
  queue_abandoned_calls:'Abandoned calls',
  queue_active_calls:'Active calls',
  agents_logged_into_queue:'Agents logged into the queue',
  agents_logged_out_of_queue:'Agents logged into the queue',
  stats_tab:'Stats',

  calls_tab:'Calls',
  all_agents:' All Agents',



  /******POPUPS*****/
  add_a_new_contact:'Add a New Contact',
  contact_info:'Contact Information',
  want_to_know_who_is_calling:'Want to know who is calling you?',
  messaging:'Messaging',
  want_to_chat_with_this_person:'Want to chat and e-mail this person?',
 
  visibility:'Visibility',
  add_to_favorites:'add to favorites group',
  phones:'Phones',
  add_contact_phone_to_make_calls:'Add contact phone to make calls',
  google_talk:'GoogleTalk (JID)',
  add_contact:'Add Contact',
  save_changes:'Save Changes',


  sign_out:'Sign out',

  Message:'Message',
  message_individual:'This chat message will be sent to each team member individually.',
  Security:'Security',
  visible_to_entire:'Visible to entire company',
  job_is_done:'Job is done?',
  click_to_delete:'Click here to delete this team and say goodbye.',
  create_team:'Create Team',
  send_message:'Send Message',
  delete_group:'Delete Group',
  delete_word:'Delete',
  team_description:'Team description is used for search and provides useful information to the team members.',
  open:'Open',
  old:'Old',
  send:'Send',
  file_share:'File Share',
  sort_by_name:'Sort By Name',
  sort_by_call_status:'Sort By Call Status',
  sort_by_chat_status:'Sort By Chat Status',
  /****Phone Notifications ***/
  clear_all:'Clear All',
  /***page**/
  page:'Page',
  group_page:'Group Page',
  group_intercom:'Group Intercom',
  group_voicemail:'Group Voicemail',
  tab_shows_group_call_members:'this tab shows group call members. No group call at this moment',
  group_info: 'Info',
  no_active_call:'No active call',

  /****DOCK AREA *****/
  parked_calls:'Parked Calls',
  no_calls_on_park:'no calls on park',

  no_voicemails:'No Voicemails In View',
  no_voicemails_between:'There are currently no voicemails in the system between you and',


  
  no_recent_calls:"No Recent Calls",

  Mute:'Mute',
  Park:'Park',
  Hold:'Hold',
  Talk:'Talk',
  not_an_agent:'Not an agent',
  no_queues:'No queues...',
  Remove:'Remove',
  Edit:'Edit',
  Intercom:'Intercom',
  Business:'Business',
  Upload:'Upload',
  edit_contact: 'Edit Contact',
  delete_contact_and_history:'Delete Contact  & History',
  created_by:'Created by',
  zoom_your_meeting_will_begin:"Your meeting will begin in 30 seconds. If your meeting doesn't begin automatically, please use this",
  call_back:'Call Back',
  Reject:'Reject',
  Play:'Play',
  Show:'Show',
  conference_room:'Conference Room',
  on_call:'on call',
  recent_contacts:'Contacts',
  contact_name_status:'Contact name (call status / HUD status)',
  recent_groups:'Groups',
  recent_group_name_members:'Group name (# of members)',
  recent_queues:'Queues',
  recent_queue_name_status:'Queue name (status)',
  recent_conferences:'Conferences',
  recent_conference_room_extension:'Conference Room (extension number)',
  members_on_call:'member(s) on a call',
  nothing_found:'Nothing found',
  characters_lefts:'characters left',
  no_recent_calls_in_view:"No Recent Calls in View",
  Reporting:'Reporting',
  pbxtra_systems_come: 'PBXtra systems come installed by default with incredibly robust reporting tools.',
  Holding:'Holding',
  Abandon:'Abandon',
  Complete:'Complete',
  Reset_word:'Reset',
  Agent_Name:'Agent Name',
  Talk_IDLE:'Talk / Idle',
  Idle:'Idle',
  other_queues:'Other queues',
  agent_of_queue_only:'Agent of this queue only',
  current_queue_call:'Current queue calls',
  no_calls:'no calls',

  /***** NO PERMISSION *****/
  sorry_no_authorization_header:'We are so sorry. You are not authorized to use the fonality web client at this time.',
  WHY:'WHY?',
  no_valid_license:'You have no valid license',
  SUGGESTION:'SUGGESTION',
  if_this_is_an_error:'if you think this is an error, or you would like to request participation, please contact your system administrator for further assistance',

  Reset_Stats:'Reset Stats',
  start:'Start',
  stop:'Stop',
  take:'Take',
  dock:'Dock',
  undock:'Undock',
  reason:'Reason',
  select_logout_reason:'Select logout reason',
  total_calls:'Total Calls',
  calls_holding:'Calls Holding',
  call_on_park:'call on park',
  calls_on_park:'calls on park',
  none:'None',
  room_is_free:'Room is free and you can do it',
  active_agents:'Active Agents',
  logged_in_agents:'Logged-in Agents',
  file_share_to:'File Share To',
  add_message_to_shared_files:'Add message to shared files or send message alone',
  items:'items',
  items_found:'items_found',
  download_current:'Download Current',
  attachments:'Attachments',
  attach:'Attach',
  auto_delete:'Auto Delete',
  file:'File',
  bytes:'bytes',
  Preview:'Preview',
  Previous:'Previous',
  Next:'Next',
  share_message_and_files:'Share Message & Files',
  time_to_goodbye:'Time to say GoodBye...',
  expand_team:'Expand Team',
  build_team:'Build the Team',
  in_queue:'In Queue',
  calls_in_queue_longest_wait:'call(s) in queue with the longest wait time of',
  nobody_is_waiting:'Nobody is waiting',
  active_calls_answered:'Active Calls (Answered)',
  active_calls_in_queue_longest_wait:'active call(s) in queue with the longest call time of',
  no_active_calls:'No active calls',
  

  call_management:'Call Management',
  call_members:'Call Members',
  contacts_talking:'These contacts are talking',
  barging:'Baring',
  barge:'Barge',
  transfer:'Transfer',
  whisper:'Whisper',
  monitor:'Monitor',
  barged_by:'Barged By',
  contacts_barge_call:'Contacts who barge the call',
  call_transfer:'Call Transfer',
  contact_to_transfer:'Contact to Transfer',
  transfer_selected_person:'This person will be transferred to the selected destination',
  destination:'Destination',
  office_destination:'Office Destination',
  call_transfer_destination:'Call will be transferred to this contact',
  transfer_options:'Transfer Options',
  primary_extension:'Primary extension',
  voicemail_box:'Voicemail box',

  are_you_ready:'Are you Ready',
  call_transfer_to_conference:'Call will be transferred to this conference',
  contacts_will_be_transfered_to_conference:'These contacts will be transferred to conference room',
  Options:'Options',
  add_yourself_to_conference:'Add yourself to the conference',
  join_me_as_well:'Join me as well',
  transfer_to_conference_room:'Transfer to Conference Room',
  search_by_room_or_person:'Search by room or person',
  attach_files_to_share:'Attach files to share',
  schedule_move_to_trash:'Schedule move to trash',
  Call_Later:'Call Later',
  Skip:'Skip',
    
  },

	/*****Japanese Language******/
	'jp':{
	
	/******global*****/
	contacts:'Contacts',
	Groups:'Groups',
	group: 'ã‚°ãƒ«ãƒ¼ãƒ—',
	Conferences:'Conferences',
	queues:'ã‚­ãƒ¥ãƒ¼',
	member:'',
	Call:'å‘¼å‡º',
	chat:'ãƒ�ãƒ£ãƒƒãƒˆ',
	recordings:'éŒ²éŸ³',
	cancel:'ã‚­ãƒ£ãƒ³ã‚»ãƒ«',
	select:'é�¸æŠž',
	clear_selection:'é�¸æŠžè§£é™¤',

	/****************ME LABELS******************/
	avatar_hover_menu: 'å†™çœŸãƒ›ãƒ�ãƒ¼ãƒ¡ãƒ‹ãƒ¥ãƒ¼é�…å»¶',
	enable_box: 'ãƒœãƒƒã‚¯ã‚¹æœ‰åŠ¹åŒ–',
	reset_app_menu_order: 'ã‚¢ãƒ—ãƒªãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚ªãƒ¼ãƒ€ãƒ¼ã‚’ãƒªã‚»ãƒƒãƒˆ',
	sound_quality: 'éŸ³è³ªè¨­å®š',
	web_phone_state: 'ã‚¦ã‚§ãƒ–ãƒ•ã‚©ãƒ³çŠ¶æ…‹',
	registered: 'ç™»éŒ²ã�šã�¿',
	microphone: 'ãƒžã‚¤ã‚¯ãƒ­ãƒ›ãƒ³',
	custom_message:'ã‚«ã‚¹ã‚¿ãƒ ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸',
	interface_word:'ã‚¤ãƒ³ã‚¿ãƒ•ã‚§ãƒ¼ã‚¹',
	application_tuning:'ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³ã�®ãƒ�ãƒ¥ãƒ¼ãƒ‹ãƒ³ã‚°',
	me: 'è‡ªå¸­',
	all: 'å…¨å¸­',
	name: 'å��ç§°',
	extension: 'å†…ç·š',
	call_status: 'ç«¯æœ«çŠ¶æ…‹',
	hud_status: 'HUD çŠ¶æ…‹',
	available: 'ã‚ªãƒ³ãƒ©ã‚¤ãƒ³/ã‚ªãƒ•ãƒ©ã‚¤ãƒ³',
	away:'é›¢å¸­',
	busy:'å�–ã‚Šè¾¼ã�¿ä¸­',
	favorites: 'ã‚ˆã��ä½¿ã�†ç«¯æœ«',
	external: 'å¤–éƒ¨ã‚³ãƒ³ã‚¿ã‚¯ãƒˆ',
	my_department: 'éƒ¨é–€',
	my_department_collaborate: 'éƒ¨é–€ã�®ãƒ¡ãƒ³ãƒ�',
	all_other_departments: 'å…¨ã�¦ã�®ä»–éƒ¨é–€',
	other_departments: 'ä»–éƒ¨é–€',
	my_teams: 'ãƒ�ãƒ¼ãƒ ',
	teams_managed_by_me:'ç®¡ç�†ãƒ�ãƒ¼ãƒ ',
	shared:'ã‚·ã‚§ã‚¢ãƒ�ãƒ¼ãƒ ',
	member_of_teams: 'ç§�ã�¯ãƒ�ãƒ¼ãƒ ãƒ¡ãƒ³ãƒ�ã�§ã�™',
	others:'ã��ã�®ä»–',
	teams_visible_to_everyone:'ä»–ã�«è¦‹ã�ˆã‚‹ãƒ�ãƒ¼ãƒ ',
	//call_status:'å‘¼çŠ¶æ…‹',
	members:'ãƒ¡ãƒ³ãƒ�ãƒ¼',
	custom_status:'ãƒžã‚¤ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸',
	location: 'ãƒžã‚¤ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸',
	carrier: 'é€šä¿¡äº‹æ¥­è€…',
	hud_mobile: 'HUDãƒ¢ãƒ�ã‚¤ãƒ«ã‚½ãƒ•ãƒˆãƒ•ã‚©ãƒ³',
	hud_web:'HUDWebã‚½ãƒ•ãƒˆãƒ•ã‚©ãƒ³',
	office:'ã‚ªãƒ•ã‚£ã‚¹',
	chat_status: 'ãƒ�ãƒ£ãƒƒãƒˆçŠ¶æ…‹',
	place_a_call: 'ç™ºä¿¡',
	phone_number:'é›»è©±ç•ªå�·',
	cuurent_call:'é€šè©±æ™‚é–“',
	transfer:'è»¢é€�',
	conf_room:'é›»è©±ä¼šè­°',
	park:	'ãƒ‘ãƒ¼ã‚¯',
    hold:	'ä¿�ç•™',
    REC:	'éŒ²éŸ³',
    move:	'ãƒ­ã‚±ãƒ¼ã‚·ãƒ§ãƒ³ç§»å‹•',
    end:	'çµ‚äº†',
    accept: 'è¨±å®¹',
    decline:'æ‹’å�¦',
    talk:'ã€€é€šè©±ä¸­',
    recent_calls:'æœ€è¿‘ã�®é€šè©±',
	date:'æ—¥',
	time:'æ™‚',
	today:'ä»Šæ—¥' , 
	yesterday:'æ˜¨æ—¥',
	AM: 'å�ˆå‰�',
	PM:	'å�ˆå¾Œ',
	from:	'ç™ºä¿¡å…ƒ',
	you:	'ã�‚ã�ªã�Ÿ',
	to:	'é€šè©±ç›¸æ‰‹',
	duration:	'é€šè©±æ™‚é–“',
	preferences:	'HUDWebæƒ…å ±',
	general:	'ä¸€èˆ¬',
	language:	'è¨€èªž',
    autoclear_search:	'è‡ªå‹•ã‚¯ãƒªã‚¢æ¤œç´¢',
    autoclear_after:'è‡ªå‹•ã‚¯ãƒªã‚¢æ¤œç´¢',
    seconds: 'ç§’',
    avatar_hover_menu_delay:	'å†™çœŸãƒ›ãƒ�ãƒ¼ãƒ¡ãƒ‹ãƒ¥ãƒ¼é�…å»¶',
    enable_box:	'ãƒœãƒƒã‚¯ã‚¹æœ‰åŠ¹åŒ–',
    reset_app_menu_order:  'ã‚¢ãƒ—ãƒªãƒ¡ãƒ‹ãƒ¥ãƒ¼ã‚ªãƒ¼ãƒ€ãƒ¼ã‚’ãƒªã‚»ãƒƒãƒˆ',
    sound_quality:'éŸ³è³ªè¨­å®š',
    sound_settings:'éŸ³ã�®è¨­å®š',
	sound_quality_setting: 	'éŸ³è³ªè¨­å®š',
	speaker: 'ã‚¹ãƒ”ãƒ¼ã‚«ãƒ¼',
  	echo:	'ã‚¨ã‚³ãƒ¼',
  	device:'ç«¯æœ«',
  	select_device_to_use:'åˆ©ç”¨ãƒ‡ãƒ�ã‚¤ã‚¹è¨­å®š',
  	wave_mapper:'ã‚¦ã‚§ãƒ–ãƒ»ãƒžãƒƒãƒ‘ãƒ¼',
  	input_devices:	'å…¥åŠ›ãƒ‡ãƒ�ã‚¤ã‚¹',
    output_devices:	'å‡ºåŠ›ãƒ‡ãƒ�ã‚¤ã‚¹',
    ring_devices:	'ãƒªãƒ³ã‚°ãƒ‡ãƒ�ã‚¤ã‚¹',
	weblauncher:	'ã‚¦ã‚§ãƒ–ãƒ©ãƒ³ãƒ�ãƒ£ãƒ¼',
	general_settings:'ä¸€èˆ¬è¨­å®š',
    weblauncher_profile:'ã‚¦ã‚§ãƒƒãƒ–ãƒ©ãƒ³ãƒ�ãƒ£ãƒ¼ãƒ—ãƒ­ãƒ•ã‚¡ã‚¤ãƒ«',
	launch_page_when_answered:'ç�€ä¿¡å¿œç­”æ™‚ã‚¦ã‚§ãƒ–è¡¨ç¤º',
	outbound_calls:'ã‚¢ã‚¦ãƒˆãƒ�ãƒ³ãƒ‰ã‚³ãƒ¼ãƒ«',
	outbound_calls_settings:'ã‚¢ã‚¦ãƒˆãƒ�ãƒ³ãƒ‰è¨­å®š',
	launch_page_during_calls: 'ç™ºä¿¡æ™‚ã‚¦ã‚§ãƒ–è¡¨ç¤º',
	launch_page_after_hang_up:'åˆ‡æ–­æ™‚ã‚¦ã‚§ãƒ–è¡¨ç¤º',
	silent:'ã‚µã‚¤ãƒ¬ãƒ³ãƒˆ',
	auto_launch:'è‡ªå‹•è¡¨ç¤º',
	inbound_calls:'ã‚¤ãƒ³ãƒ�ãƒ³ãƒ‰ã‚³ãƒ¼ãƒ«',
	inbound_call_settings:'ã‚¤ãƒ³ãƒ�ãƒ³ãƒ‰ã‚³ãƒ¼ãƒ«è¨­å®š',
	web_launcher_variables:'ã‚¦ã‚§ãƒ–ãƒ©ãƒ³ãƒ�ãƒ£ãƒ¼ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿',
	web_launcher_var_desc:'ã‚¦ã‚§ãƒ–ãƒ©ãƒ³ãƒ�ãƒ£ãƒ¼ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿è¨˜è¿°',
	variables:'ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿',
	description:'ãƒ‘ãƒ©ãƒ¡ãƒ¼ã‚¿èª¬æ˜Ž',
	inbound:'ã‚¤ãƒ³ãƒ�ãƒ³ãƒ‰',
	outbound:'ã‚¢ã‚¦ãƒˆãƒ�ãƒ³ãƒ‰',
	queues:'ã�¾ã�Ÿã�¯ã‚­ãƒ¥ãƒ¼ç�€ä¿¡',
    public_team: '',
    team: '',
	wl_var_desc_username_accounts:'èª�è¨¼ã‚’è¦�æ±‚ã�™ã‚‹ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã�®ãƒ¦ãƒ¼ã‚¶ãƒ�ãƒ¼ãƒ ',
	wl_var_desc_duration:'é€šè©±ã�®çµŒé�Žæ™‚é–“ï¼ˆç§’ï¼‰',
	wl_var_desc_name_of_party:'æŽ¥ç¶šå…ˆç•ªå�·',
	wl_var_desc_call_type:'å‘¼ç¨®åˆ¥',
	wl_var_desc_your_ext:'å†…ç·šç•ªå�·',
	wl_var_desc_name_of_your_party:'æŽ¥ç¶šå…ˆç•ªå�·',
	wl_var_desc_your_password:'èª�è¨¼ã‚’è¦�æ±‚ã�™ã‚‹ã‚¢ã‚«ã‚¦ãƒ³ãƒˆã�®ãƒ‘ã‚¹ãƒ¯ãƒ¼ãƒ‰',
	wl_var_desc_caller_number:'%%caller_number%%æ–‡å­—åˆ—ã�®å‰Šé™¤ã�•ã‚Œã�Ÿéƒ¨åˆ†',
	waiting:'å¾…ã�¡å�ˆã‚�ã�›ä¸­',
	calls:'å‘¼',
	avg_wait:'å¹³å�‡å¾…',
	avg_talk:'å¹³å�‡é€šè©±æ™‚é–“',
	minutes:'åˆ†',
	abandoned:'é€”ä¸­æ”¾æ£„',
	avatar_upload: 'å†™çœŸ ã‚¢ãƒƒãƒ—ãƒ­ãƒ¼ãƒ‰',
	first_name:	'å��',
 	last_name:	'å§“',
	display_name:'HUDwebè¡¨ç¤ºå��ç§°',
    email: 'eãƒ¡ãƒ¼ãƒ«',
	mobile:	'æ�ºå¸¯ç•ªå�·',
    voicemail:	'ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ‰ãƒ¬ã‚¹',
    business_phone:	'ãƒ“ã‚¸ãƒ�ã‚¹ç•ªå�·',
    extension:	'å†…ç·šç•ªå�·',
   IMS:	'IMS',
   JID:	'JID',
   my_department:'æ‰€å±žéƒ¨é–€',
   alerts: 'ã‚¢ãƒ©ãƒ¼ãƒˆ',
   configure_desktop_alerts: 'ãƒ‡ã‚¹ã‚¯ãƒˆãƒƒãƒ—ã‚¢ãƒ©ãƒ¼ãƒˆè¨­å®š',
   show_alerts:	'ã‚¢ãƒ©ãƒ¼ãƒˆè¡¨ç¤º',
   show_status_when_busy:'ãƒ“ã‚¸ãƒ¼æ™‚ã‚¢ãƒ©ãƒ¼ãƒˆè¡¨ç¤º',
   show_when_app_in_focus:'ã‚¢ãƒ—ãƒªã‚±ãƒ¼ã‚·ãƒ§ãƒ³ãƒ•ã‚©ãƒ¼ã‚«ã‚¹æ™‚è¡¨ç¤º',
   voicemail_alerts:'ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã‚¢ãƒ©ãƒ¼ãƒˆ',
   configure_desktop_alerts:'ãƒ‡ã‚¹ã‚¯ãƒˆãƒƒãƒ—ã‚¢ãƒ©ãƒ¼ãƒˆè¨­å®š',
   show_when_new_voicemail: 'æ–°ç�€ã�®ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã‚’è¡¨ç¤º',
   call_alerts: 'é€šè©±ã‚¢ãƒ©ãƒ¼ãƒˆ',
   configure_call_desktop_alerts:'é€šè©±ãƒ‡ã‚¹ã‚¯ãƒˆãƒƒãƒ—ã‚¢ãƒ©ãƒ¼ãƒˆè¨­å®š',
   type:'ã‚¿ã‚¤ãƒ—',
   incoming_calls:	'ç™ºä¿¡é€šè©±',
   outbound_calls:	'ç�€ä¿¡é€šè©±',
   display_for:	'è¡¨ç¤ºæ�¡ä»¶',
   all_my_calls:	'å…¨ã�¦ã�®é€šè©±ã‚’è¡¨ç¤ºã�™ã‚‹',
   only_for_known_numbers:	'æ—¢çŸ¥ã�®ç•ªå�·ã�®ã�¿è¡¨ç¤ºã�™ã‚‹',
   never_display:	'è¡¨ç¤ºã�—ã�ªã�„',
   entire_call_recommended: 'å¸¸ã�«è¡¨ç¤º',
   while_phone_is_ringing:' å‘¼ã�³å‡ºã�—ä¸­è¡¨ç¤º',
   queue_alerts: 'ã‚­ãƒ¥ãƒ¼ã‚¢ãƒ©ãƒ¼ãƒˆ',
   configure_queue_not_and_desktop_alerts: 'ã‚­ãƒ¥ãƒ¼é€šçŸ¥ã�¨ãƒ‡ã‚¹ã‚¯ãƒˆãƒƒãƒ—ã‚¢ãƒ©ãƒ¼ãƒˆè¨­å®š',
   select_all: 'å…¨ã�¦é�¸æŠž',
   long_waiting_call: 'é•·æ™‚é–“å¾…ã�¡å�ˆã‚�ã�›',
   notifications: 'é€šçŸ¥',
   desktop_alerts: 'ãƒ‡ã‚¹ã‚¯ãƒˆãƒƒãƒ—ã‚¢ãƒ©ãƒ¼ãƒˆ',
   abandoned_calls: 'é€”ä¸­æ”¾æ£„',
   cp: 'ï¼£ï¼°ç”»é�¢',
   HOME: 'HOME',
   user_control_panel:'ãƒ¦ãƒ¼ã‚¶ã‚³ãƒ³ãƒˆãƒ­ãƒ¼ãƒ«ãƒ‘ãƒ�ãƒ«',
   features: 'æ©Ÿèƒ½ï¼ˆFMFMç­‰ï¼‰',
   ACD: 'ACD',
   auto_call_distro:'è‡ªå‹•é€šè©±æŒ¯ã‚Šåˆ†ã�‘',
   about: 'Fonalityæƒ…å ±',
   fonality_web_client:'ãƒ•ã‚©ãƒŠãƒªãƒ†ã‚£WEBã‚¯ãƒ©ã‚¤ã‚¢ãƒ³ãƒˆ',
   fon_cloud_service:'ãƒ•ã‚©ãƒŠãƒªãƒ†ã‚£ã‚¯ãƒ©ã‚¦ãƒ‰ã‚µãƒ¼ãƒ“ã‚¹',
   current_call:'é€šè©±é€šã�®å‘¼',
   sounds: 'éŸ³',
   sound_settings_general_desc:'ãƒ�ãƒ£ãƒƒãƒˆã�¨é€šçŸ¥ã�®ã‚µã‚¦ãƒ³ãƒ‰è¨­å®š',
   enable_chat_sound:'ãƒ�ãƒ£ãƒƒãƒˆã‚µã‚¦ãƒ³ãƒ‰ã‚’ã‚ªãƒ³ã�«ã�™ã‚‹',
   on_message_received:'ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸å�—ä¿¡æ™‚',
   on_sent_message:'ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸é€�ä¿¡æ™‚',
   call_preferences:'é€šè©±ã�®è¨­å®š',
   call_log_size:'é€šè©±ãƒ­ã‚°ãƒ•ã‚¡ã‚¤ãƒ«ã‚µã‚¤ã‚º',
   busy_ring_back:'ãƒ“ã‚¸ãƒ¼ãƒªãƒ³ã‚°ãƒ�ãƒƒã‚¯ãƒˆãƒ¼ãƒ³',
   auto_away: 'è‡ªå‹•é›¢å¸­',
   auto_away_settings_desc: 'è‡ªå‹•é›¢å¸­è¨­å®š',
   auto_away_after: 'è‡ªå‹•é›¢å¸­å¾Œ',
   enable_auto_away:'è‡ªå‹•é›¢å¸­ã‚’æœ‰åŠ¹',
   dashboard:'ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰',
   dashboard_setting: 'ãƒ€ãƒƒã‚·ãƒ¥ãƒœãƒ¼ãƒ‰ã�®è¨­å®š',
   use_column_layout: 'åˆ—ã�®ãƒ¬ã‚¤ã‚¢ã‚¦ãƒˆã‚’ä½¿ç”¨ã�—ã�¦',
   web_launcher:'ã‚¦ã‚§ãƒ–ãƒ©ãƒ³ãƒ�ãƒ£ãƒ¼',
   web_launcher_profile:'ã‚¦ã‚§ãƒƒãƒ–ãƒ©ãƒ³ãƒ�ãƒ£ãƒ¼ãƒ—ãƒ­ãƒ•ã‚¡ã‚¤ãƒ«',
   web_launcher_on_new_calls:'ç�€ä¿¡æ™‚ã‚¦ã‚§ãƒ–è¡¨ç¤º',
   web_launcher_on_hang_ups:'åˆ‡æ–­æ™‚ã‚¦ã‚§ãƒ–è¡¨ç¤º',
   queue_summary_stats:'ã‚­ãƒ¥ãƒ¼è¦�ç´„çµ±è¨ˆ',
   highlight_threshold:'ã�—ã��ã�„å€¤ã‚’å¼·èª¿è¡¨ç¤ºã�—ã�¾ã�™ã€‚ STATã�Œå¼·èª¿ã�•ã‚Œã‚‹ã�“ã�¨ã�¯ã�‚ã‚Šã�¾ã�›ã‚“å ´å�ˆã�¯ã€�0ã�«è¨­å®šã�—ã�¦ã��ã� ã�•ã�„ã€‚',
   my_account:'ã‚¢ã‚«ã‚¦ãƒ³ãƒˆ',
   my_account_info:'ã‚¢ã‚«ã‚¦ãƒ³ãƒˆæƒ…å ±',
   login:'ãƒ­ã‚°ã‚¤ãƒ³',
   Server:'ã‚µãƒ¼ãƒ�ãƒ¼',
   my_personal_info: 'å€‹äººæƒ…å ±',
   my_personal_info_desc: 'ã�“ã�®æƒ…å ±ã�¯ã€�ã‚³ãƒ³ã‚¿ã‚¯ãƒˆãƒªã‚¹ãƒˆã�«è¡¨ç¤ºã�•ã‚Œã�¾ã�™',
   avatar:'å†™çœŸ',
   reset_alert_position:'ã‚¢ãƒ©ãƒ¼ãƒˆä½�ç½®ã‚’ãƒªã‚»ãƒƒãƒˆ',
   features_desc_sum:'é›»è©±ã‚’ä½¿ã�†å¤šã��ã�®æ©Ÿèƒ½',
   fon_pbx_control_server: 'FONALITYã�®PBXç®¡ç�†ã‚µãƒ¼ãƒ�ãƒ¼',
   fon_pbx_server:'FONALITYã�®PBXã‚µãƒ¼ãƒ�ãƒ¼',
   fon_plugin:'FONALITYãƒ—ãƒ©ã‚°ã‚¤ãƒ³',
   version:'ãƒ�ãƒ¼ã‚¸ãƒ§ãƒ³',
   fdp_version:'FDPã�®ãƒ�ãƒ¼ã‚¸ãƒ§ãƒ³',
   hud_server_version:'HUDã‚µãƒ¼ãƒ�ãƒ¼ãƒ�ãƒ¼ã‚¸ãƒ§ãƒ³',
   fon_core_version:'FONcoreãƒ�ãƒ¼ã‚¸ãƒ§ãƒ³',
   phone: 'é›»è©±',    
   me:'è‡ªå¸­',
   call_and_recordings:'é€šè©±ã�¨éŒ²éŸ³',
   conferencing:'ä¼šè­°ä¸­',
   callcenter:'ã‚³ãƒ¼ãƒ«ã‚»ãƒ³ã‚¿ãƒ¼',
   zoom:'ãƒ“ãƒ‡ã‚ªä¼šè­°',
   search:'æ¤œç´¢',
   box:'ãƒœãƒƒã‚¯ã‚¹',
   /***Left Bar Navigation **/
   all:'å…¨å¸­',
   recent:'æœ€è¿‘ã�®',
   new_word: 'æ–°ã�—ã�„',
   loading:'ãƒ­ãƒ¼ãƒ‡ã‚£ãƒ³ã‚°',
   offline:'ã‚ªãƒ•ãƒ©ã‚¤ãƒ³ã�§',
   events: 'ã‚¤ãƒ™ãƒ³ãƒˆ',
   add_someone:'ä»»æ„�ã�®ãƒ¡ãƒ³ãƒ�è¿½åŠ ',

       /**** ZOOM ****/
      video_collaboration_summary: "ã�Šå®¢æ§˜ã�¯å¼Šç¤¾ã�®ç”¨æ„�ã�™ã‚‹ãƒ“ãƒ‡ã‚ªé€£æ�ºã‚µãƒ¼ãƒ“ã‚¹ã‚’ã�”åˆ©ç”¨ã�—ã�¦ã�„ã�Ÿã� ã��ã�“ã�¨ã�Œã�§ã��ã�¾ã�™ã€‚æœ¬æ©Ÿèƒ½ã�¯æ—¥æœ¬å›½å†…ã�«ã�‚ã‚‹ç¤¾å†…å¤–ã�«ã�Šã�„ã�¦ãƒ“ãƒ‡ã‚ªä¼šè­°ã‚’é–‹å‚¬ã�™ã‚‹ã�“ã�¨ã�Œã�§ã��ã�¾ã�™ã€‚ã�‚ã‚�ã�›ã�¦ã‚·ã‚§ã‚¢ã‚¹ã‚¯ãƒªãƒ¼ãƒ³æ©Ÿèƒ½ã‚‚ã�”åˆ©ç”¨ã�„ã�Ÿã� ã�‘ã�¾ã�™ã€‚",
      join_summary:"ãƒ“ãƒ‡ã‚ªä¼šè­°ã‚’åˆ©ç”¨ã�™ã‚‹ã�Ÿã‚�ã�«ã�¯ãƒŸãƒ¼ãƒ†ã‚£ãƒ³ã‚°ï¼©ï¼¤ã‚’å…¥åŠ›ã�—ã€�'å�‚åŠ ã�™ã‚‹'ãƒœã‚¿ãƒ³ã‚’ã‚¯ãƒªãƒƒã‚¯ã�—ã�¦ã��ã� ã�•ã�„ã€‚",
      create_summary:"ä¸‹è¨˜ã�®ï¼“ã�¤ã�®ã‚¿ã‚¤ãƒ—ã�‹ã‚‰ãƒ“ãƒ‡ã‚ªã‚»ãƒƒã‚·ãƒ§ãƒ³ã‚’é�¸æŠžã�—ã€�åˆ©ç”¨ã�™ã‚‹ã�“ã�¨ã�Œã�§ã��ã�¾ã�™ã€‚",
      create:'ã‚¯ãƒªã‚¨ãƒ¼ãƒˆ',
      start_screen_share_only:"ã‚·ã‚§ã‚¢ã‚¹ã‚¯ãƒªãƒ¼ãƒ³ã�®ã�¿ã�§é–‹å§‹",
      start_with_video:"videoä¼šè­°é–‹å§‹",
      join_now:'å�‚åŠ ã�™ã‚‹',
      join:'å�‚åŠ ',
      meeting_id:'ãƒŸãƒ¼ãƒ†ã‚£ãƒ³ã‚°ï¼©ï¼¤',
      zoom_created:'ãƒ“ãƒ‡ã‚ªä¼šè­°ã�Œä½œæˆ�ã�•ã‚Œã�¦ã�„ã�¾ã�™',
      link:'ãƒªãƒ³ã‚¯',
      link_to_join:'å�‚åŠ ã�™ã‚‹ãƒªãƒ³ã‚¯:',
	        
      /*****Search WIdget ******/
      type_for_results:'å��ç§°ã€€ã�¾ã�Ÿã�¯ç•ªå�·',
      search_to_start_convo:'ä¼šè©±ã‚’å§‹ã‚�ã‚‹ã�Ÿã‚�ã�«æ¤œç´¢ã�™ã‚‹',
      type_subject_name:'ã‚³ãƒ³ã‚¿ã‚¯ãƒˆå��ç§°,ãƒ�ãƒ¼ãƒ å��ç§°ã€�ã‚­ãƒ¥ãƒ¼å��ç§°ã�¾ã�Ÿã�¯ä¼šè­°å®¤å��ç§°...',
      call_log_tab:'é€šè©±å±¥æ­´',
      voicemail_tab:'ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«',
      my_recordings_tab:'é€šè©±éŒ²éŸ³',
      action:'å‹•ä½œ',
      no_transcriptions:'ãƒ†ã‚­ã‚¹ãƒˆå¤‰æ�›ã�¯ã�‚ã‚Šã�¾ã�›ã‚“',
      to:'ã�‹ã‚‰ç›¸æ‰‹',
      from:'ã�‹ã‚‰',

      mark_all_incoming_vm_read:'æ—¢èª­ã�®ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã�«ãƒžãƒ¼ã‚¯ã�™ã‚‹ ',
      mark_all_incoming_vm_unread:'æœªèª­ã�®ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã�«ãƒžãƒ¼ã‚¯ã�™ã‚‹ ',
      delete_all_incoming_read:'æ—¢èª­ã�®ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã‚’å‰Šé™¤ã�™ã‚‹ ', 

      sort_newest_first:'æ–°ã�—ã�„é †',
      sort_alphabetically:'ã‚¢ãƒ«ãƒ•ã‚¡ãƒ™ãƒƒãƒˆé † ',
      sort_oldest_first:'å�¤ã�„é †',
      sort_read_status:'æ—¢èª­çŠ¶æ…‹',
  
       /*****Conferences*******/
      conferencing:'ä¼šè­°ä¸­',
      my_rooms:'å€‹äººã�®ä¼šè­°å®¤',
      all_rooms:'å…¨ã�¦ã�®ä¼šè­°å®¤',
      find_free_room:'ç©ºã��ä¼šè­°å®¤ï¼†å�‚åŠ ',
      sort_room:'åˆ©ç”¨ä¸­ã�§ä¸¦ã�¹æ›¿ã�ˆ',
      sort_room_by_location:'ãƒ­ã‚±ãƒ¼ã‚·ãƒ§ãƒ³ ',
      sort_by_activity:'åˆ©ç”¨ä¸­',
      sort_by_room_number:'éƒ¨å±‹ç•ªå�·ã�§ä¸¦ã�¹æ›¿ã�ˆ',
      conf_summary_my_rooms:'å�‚åŠ æŒ‡ç¤ºã€�é€€å‡ºæŒ‡ç¤ºç­‰ã�®æ‹¡å¼µæ¨©é™�ã‚’åˆ©ç”¨ã�§ã��ã‚‹ä¼šè­°å®¤',
      conf_summary_all_rooms:'å�‚åŠ æŒ‡ç¤ºã€�é€€å‡ºæŒ‡ç¤ºç­‰ã�®æ‹¡å¼µæ¨©é™�ã�Œåˆ¶é™�ã�•ã‚Œã�¦ã�„ã‚‹å�¯èƒ½æ€§ã�Œã�‚ã‚‹ä¼šè­°å®¤',
      conf_members:'Conference Members',
      free_room:'ç©ºå®¤',
      occupied:'åˆ©ç”¨ä¸­',
      talking:'é€šè©±ä¸­',
      rooms:'éƒ¨å±‹æ•°',
      room:'ä¼šè­°å®¤',
      total:'ç·�å‘¼æ•°',
      you_are_on_call:'ã�‚ã�ªã�Ÿã�¯é›»è©±ä¼šè­°ã�«å�‚åŠ ã�—ã�¦ã�„ã�¾ã�™',
      not_a_member_of_conference:'ã�‚ã�ªã�Ÿã�¯ã�“ã�®é›»è©±ä¼šè­°ã�«å�‚åŠ ã�—ã�¦ã�„ã�¾ã�›ã‚“ã€‚',
      leave:'é€€å‡º',
      conference_member:'ä¼šè­°ãƒ¡ãƒ³ãƒ�.',
      only_see_messages_during_chat:'ä¼šè­°é€šè©±ä¸­ã�«é€�ä¿¡ã�•ã‚Œã�Ÿãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã� ã�‘ã‚’è¦‹ã‚‹ã�“ã�¨ã�Œã�§ã��ã�¾ã�™ã€‚',
      join_to_chat:'ãƒ�ãƒ£ãƒƒãƒˆã‚’ä½¿ç”¨ã�™ã‚‹ã�Ÿã‚�ã�«é›»è©±ä¼šè­°ã�«å�‚åŠ ã�—ã�¦ä¸‹ã�•ã�„ ',

      /***Conversation***/
      department:'éƒ¨é–€',
      member_of_department:'ã‚³ãƒ³ã‚¿ã‚¯ãƒˆã�¯ã�“ã�®éƒ¨é–€ã�®ãƒ¡ãƒ³ãƒ�ãƒ¼',
      our_teams:'æˆ‘ã€…ã�®ãƒ�ãƒ¼ãƒ ',
      both_in_these_teams:'æˆ‘ã€…ã�¯ã€�ä¸‹è¨˜ã�®ãƒ�ãƒ¼ãƒ ã�«æ‰€å±žã�—ã�¦ã�„ã�¾ã�™',

      /*****QUEUES******/
      login_all:'ã�™ã�¹ã�¦ã�®ãƒ­ã‚°ã‚¤ãƒ³',
      logout_all:'ã�™ã�¹ã�¦ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ',

      logged_in:'ã�™ã�¹ã�¦ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ',
      Logged_out:'ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ',
      logout:'ãƒ­ã‚°ã‚¢ã‚¦ãƒˆ',
      active:'é€šè©±ä¸­',
      queue_name:'ã‚­ãƒ¥ãƒ¼å��ç§°',
      my_queue:'ã‚­ãƒ¥ãƒ¼',
      all_queues:'å…¨ã�¦ã�®ã‚­ãƒ¥ãƒ¼',
      my_status:'çŠ¶æ…‹',
      aban:'æ”¾æ£„å‘¼',
      agents:'å†…ç·š',

      queue_sort_calls_wait:'å¾…ã�¡å‘¼æ•° ',
      queue_sort_avg_wait_time:'å¹³å�‡å¾…ã�¡æ™‚é–“ (ESA)',
      queue_sort_avg_talk_time:'å¹³å�‡é€šè©±æ™‚é–“ ',
      queue_sort_total_calls:"ç·�å‘¼æ•° ï¼ˆæœ€å¾Œã�®ãƒªã‚»ãƒƒãƒˆã�‹ã‚‰ï¼‰",
      queue_abandoned_calls:'é€”ä¸­æ”¾æ£„å‘¼æ•° ',
      queue_active_calls:'é€šè©±ä¸­ã�®å‘¼æ•° ',
      agents_logged_into_queue:'Agents logged into the queue',
      agents_logged_out_of_queue:'Agents logged into the queue',

      agent_tab:'ã‚ªãƒšãƒ¬ãƒ¼ã‚¿',
      stats_tab:'çµ±è¨ˆ',
      calls_tab:'é€šè©±',
      all_agents:' ã�™ã�¹ã�¦ã�®ã‚¨ãƒ¼ã‚¸ã‚§ãƒ³ãƒˆ',


      /******POPUPS*****/
      add_a_new_contact:'æ–°ã�—ã�„é€£çµ¡å…ˆã‚’è¿½åŠ ',
      messaging:'ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸æ–¹æ³•',
      want_to_chat_with_this_person:'ã�“ã�®äººã‚’ãƒ�ãƒ£ãƒƒãƒˆã‚„é›»å­�ãƒ¡ãƒ¼ãƒ«ã�—ã�¦ã�¿ã�¾ã�›ã‚“ã�‹ï¼Ÿ',
      contact_info:'ã‚³ãƒ³ã‚¿ã‚¯ãƒˆæƒ…å ±',
      want_to_know_who_is_calling:'èª°ã�Œé›»è©±ã‚’ã�—ã�¦ã��ã�Ÿã�®ã�‹',

      visibility:'ã‚ˆã��è¦‹ã‚‹ã‚°ãƒ«ãƒ¼ãƒ—',
      add_to_favorites:'ã‚ˆã��åˆ©ç”¨ã�™ã‚‹ã‚°ãƒ«ãƒ¼ãƒ—ã�¸ã�®è¿½åŠ ',
      phones:'é›»è©±ç•ªå�·',
      add_contact_phone_to_make_calls:'å‘¼ã�³å‡ºã�—ã‚’è¡Œã�†ã�Ÿã‚�ã�«é›»è©±ã‚’é€£çµ¡å…ˆã�®è¿½åŠ ',
      google_talk:'Googleãƒˆãƒ¼ã‚¯(JID)',
      add_contact:'é€£çµ¡å…ˆã‚’è¿½åŠ ',
      save_changes:'Save Changes',
      agents:'ã‚¨ãƒ¼ã‚¸ã‚§ãƒ³ãƒˆ',
      send:'é€�ä¿¡',


      sign_out:'ã‚µã‚¤ãƒ³ã‚¢ã‚¦ãƒˆ',

      Message:'ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£',
      message_individual:'ã�“ã�®ãƒ�ãƒ£ãƒƒãƒˆãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã�¯å€‹åˆ¥ã�«å�„ãƒ�ãƒ¼ãƒ ãƒ¡ãƒ³ãƒ�ãƒ¼ã�«é€�ä¿¡ã�•ã‚Œã�¾ã�™ã€‚',
      Security:'ã‚»ã‚­ãƒ¥ãƒªãƒ†ã‚£',
      visible_to_entire:'ä¼šç¤¾å…¨ä½“ã�«è¡¨ç¤ºã�•ã‚Œã�¾ã�™',
      job_is_done:'ã‚¸ãƒ§ãƒ–ã�Œå®Ÿè¡Œã�•ã‚Œã�¾ã�—ã�Ÿã€‚?',
      click_to_delete:'ã�“ã�®ãƒ�ãƒ¼ãƒ ã‚’å‰Šé™¤ã�—ã�¦ã€�ã�•ã‚ˆã�ªã‚‰ã‚’è¨€ã�†ã�Ÿã‚�ã�«ã€�ã�“ã�“ã‚’ã‚¯ãƒªãƒƒã‚¯ã�—ã�¦ã��ã� ã�•ã�„ã€‚',
      create_team:'ãƒ�ãƒ¼ãƒ ã‚’ä½œæˆ�',
      send_message:'Send Message',
      delete_group:'Delete Group',
      delete_word:'Delete',
      team_description:'ãƒ�ãƒ¼ãƒ ã�®è©³ç´°ã�¯æ¤œç´¢ã�®ã�Ÿã‚�ã�«ä½¿ç”¨ã�•ã‚Œã�¾ã�™ã€‚',
      open:'é–‹ã��',
      file_share:'ãƒ•ã‚¡ã‚¤ãƒ«ã‚·ã‚§ã‚¢',

      sort_by_name:'ãƒ¦ãƒ¼ã‚¶å�� ',
      sort_by_call_status:'ã‚³ãƒ¼ãƒ«ã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ ',
      sort_by_chat_status:'ãƒ�ãƒ£ãƒƒãƒˆã‚¹ãƒ†ãƒ¼ã‚¿ã‚¹ ',
   

      /***page ***/
      page:'ãƒšãƒ¼ã‚¸',
      group_page:'ã‚°ãƒ«ãƒ¼ãƒ—ãƒšãƒ¼ã‚¸',
      group_intercom:'ã‚°ãƒ«ãƒ¼ãƒ—ã‚¤ãƒ³ã‚¿ãƒ¼ãƒ›ãƒ³ ',
      group_voicemail:'ã‚°ãƒ«ãƒ¼ãƒ—ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ« ',
      tab_shows_group_call_members:'ã�“ã�®ã‚¿ãƒ–ã�«ã‚°ãƒ«ãƒ¼ãƒ—ã‚³ãƒ¼ãƒ«ã�®ãƒ¡ãƒ³ãƒ�ãƒ¼ã‚’è¡¨ç¤ºã�—ã�¦ã�„ã�¾ã�™ã€‚ç�¾æ™‚ç‚¹ã�§ã�¯ã‚°ãƒ«ãƒ¼ãƒ—ã‚³ãƒ¼ãƒ«ã�¯ã�‚ã‚Šã�¾ã�›ã‚“ã€‚',
      no_active_call:'é€šè©±ã�Œã�‚ã‚Šã�¾ã�›ã‚“',

      /****phone notifications ****/
      new_call:'æ–°è¦�é€šè©±',
      old:'æœªèª­',
      clear_all:'ã�™ã�¹ã�¦ã‚’ã‚¯ãƒªã‚¢',

      /****DOCK AREA *****/
      parked_calls:'ãƒ‘ãƒ¼ã‚¯ä¿�ç•™',
      no_calls_on_park:'ãƒ‘ãƒ¼ã‚¯ä¿�ç•™ã�¯ã�‚ã‚Šã�¾ã�›ã‚“',

      file_share_message:'ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸',
      add_message_to_shared:'å…±æœ‰ãƒ•ã‚¡ã‚¤ãƒ«ã�«ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã‚’è¿½åŠ ã�—ã�Ÿã‚Šã€�å�˜ç‹¬ã�§ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã‚’é€�ä¿¡',
      auto_delete:'è‡ªå‹•å‰Šé™¤',
      never:'æ±ºã�—ã�¦',
      hours:'3æ™‚é–“å¾Œ',
  

      no_voicemails:'ãƒ“ãƒ¥ãƒ¼ã�«ã�¯ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã�Œã�‚ã‚Šã�¾ã�›ã‚“',
      no_voicemails_between:'ç�¾åœ¨ã‚·ã‚¹ãƒ†ãƒ å†…ã�«ãƒœã‚¤ã‚¹ãƒ¡ãƒ¼ãƒ«ã�¯ã�‚ã‚Šã�¾ã�›ã‚“',


      no_recent_calls:"No Recent Calls",

      Mute:'ãƒŸãƒ¥ãƒ¼ãƒˆ',
      Park:'ãƒ‘ãƒ¼ã‚¯',
      Hold:'ä¿�ç•™',
      Talk:'è©±',
      not_an_agent:'Not an agent',
      no_queues:'No queues...',
      Remove:'Remove',
      Edit:'Edit',
      Intercom:'ã‚¤ãƒ³ã‚¿ãƒ¼ã‚³ãƒ ',
      Business:'Business',
      Upload:'Upload',
      edit_contact: 'Edit Contact',
      delete_contact_and_history:'Delete Contact  & History',
      created_by:'Created by',
      zoom_your_meeting_will_begin:"Your meeting will begin in 30 seconds. If your meeting doesn't begin automatically, please use this",
      call_back:'Call Back',
      Reject:'Reject',
      Play:'Play',
      Show:'Show',
      conference_room:'Conference Room',
      on_call:'on call',
      recent_contacts:'Recent Contacts',
      contact_name_status:'Contact name (call status / HUD status)',
      recent_groups:'Recent Groups',
      recent_group_name_members:'Group name (# of members)',
      recent_queues:'Recent Queues',
      recent_queue_name_status:'Queue name (status)',
      recent_conferences:'Recent Conferences',
      recent_conference_room_extension:'Conference Room (extension number)',
      members_on_call:'member(s) on a call',
      nothing_found:'Nothing found',
      characters_lefts:'characters left',
      no_recent_calls_in_view:"ãƒ“ãƒ¥ãƒ¼ã�«ã�¯æœ€è¿‘ã�®é€šè©±ã�Œã�‚ã‚Šã�¾ã�›ã‚“",
      Reporting:'Reporting',
      pbxtra_systems_come: 'PBXtra systems come installed by default with incredibly robust reporting tools.',
      Holding:'Holding',
      Abandon:'Abandon',
      Complete:'Complete',
      Reset_word:'Reset',
      Agent_Name:'Agent Name',
      Talk_IDLE:'Talk / Idle',
      Idle:'Idle',
      other_queues:'Other queues',
      agent_of_queue_only:'Agent of this queue only',
      current_queue_call:'Current queue calls',
      no_calls:'no calls',

      /***** NO PERMISSION *****/
      sorry_no_authorization_header:'We are so sorry. You are not authorized to use the fonality web client at this time.',
      WHY:'WHY?',
      no_valid_license:'You have no valid license',
      SUGGESTION:'SUGGESTION',
      if_this_is_an_error:'if you think this is an error, or you would like to request participation, please contact your system administrator for further assistance',

      Reset_Stats:'Reset Stats',
      start:'Start',
      stop:'Stop',
      take:'Take',
      dock:'ãƒ‰ãƒƒã‚¯',
      undock:'Undock',
      reason:'Reason',
      select_logout_reason:'Select logout reason',
      total_calls:'Total Calls',
      calls_holding:'Calls Holding',
      call_on_park:'call on park',
      calls_on_park:'calls on park',
      none:'None',
      room_is_free:'Room is free and you can do it',
      active_agents:'ãƒ­ã‚°ã‚¤ãƒ³ä¸­å†…ç·šï¼š',
      logged_in_agents:'ãƒ­ã‚°ã‚¤ãƒ³ä¸­å†…ç·šï¼š',
      file_share_to:'ãƒ•ã‚¡ã‚¤ãƒ«å…±æœ‰ã�«',
      add_message_to_shared_files:'å…±æœ‰ãƒ•ã‚¡ã‚¤ãƒ«ã�«ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã‚’è¿½åŠ ã�—ã�Ÿã‚Šã€�å�˜ç‹¬ã�§ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸ã‚’é€�ä¿¡',
      items:'ã‚¢ã‚¤ãƒ†ãƒ ',
      items_found:'ã‚¢ã‚¤ãƒ†ãƒ ã�Œè¦‹ã�¤ã�‹ã‚Šã�¾ã�—ã�Ÿã€‚',
      download_current:'ç�¾åœ¨ã�®ãƒ€ã‚¦ãƒ³ãƒ­ãƒ¼ãƒ‰',
      attachments:'æ·»ä»˜',
      attach:'æ·»ä»˜ã�™ã‚‹',
      attach_files_to_share:'å…±æœ‰ã�™ã‚‹ã�Ÿã‚�ã�«ãƒ•ã‚¡ã‚¤ãƒ«ã‚’æ·»ä»˜',
      schedule_move_to_trash:'ã‚´ãƒŸç®±ã�«ç§»å‹•ã�™ã‚‹ã‚¹ã‚±ã‚¸ãƒ¥ãƒ¼ãƒ«',
      auto_delete:'è‡ªå‹•å‰Šé™¤',
      file:'File',
      bytes:'bytes',
      Preview:'ãƒ—ãƒ¬ãƒ“ãƒ¥ãƒ¼ï¼š',
      Previous:'å‰�',
      Next:'æ¬¡ã�®',
      share_message_and_files:'å…±æœ‰ãƒ¡ãƒƒã‚»ãƒ¼ã‚¸Â·ãƒ•ã‚¡ã‚¤ãƒ«',
      time_to_goodbye:'ã�•ã‚ˆã�ªã‚‰ã‚’è¨€ã�†æ™‚é–“...',
      expand_team:'ãƒ�ãƒ¼ãƒ ã‚’å±•é–‹',
      build_team:'ãƒ�ãƒ¼ãƒ ã‚’ä½œã‚‹',
      in_queue:'In Queue',
      calls_in_queue_longest_wait:'call(s) in queue with the longest wait time of',
      nobody_is_waiting:'Nobody is waiting',
      active_calls_answered:'Active Calls (Answered)',
      active_calls_in_queue_longest_wait:'active call(s) in queue with the longest call time of',
      no_active_calls:'No active calls',
      

      call_management:'Call Management',
      call_members:'Call Members',
      contacts_talking:'These contacts are talking',
      barging:'Barging',
      barge:'ã�¯ã�—ã�‘',
      transfer:'è»¢é€�',
      whisper:'ä½Žèªžã�™ã‚‹',
      monitor:'ãƒ¢ãƒ‹ã‚¿ãƒ¼',
      barged_by:'Barged By',
      contacts_barge_call:'Contacts who barge the call',
      call_transfer:'è»¢é€�',
      contact_to_transfer:'è»¢é€�ã�™ã‚‹ã�Ÿã‚�ã�«æŽ¥è§¦',
      transfer_selected_person:'ã�“ã�®äººã�¯ã€�é�¸æŠžã�•ã‚Œã�Ÿå®›å…ˆã�«è»¢é€�ã�•ã‚Œã�¾ã�™',
      destination:'ãƒ‡ã‚¹ãƒ†ã‚£ãƒ�ãƒ¼ã‚·ãƒ§ãƒ³',
      office_destination:'Office Destination',
      call_transfer_destination:'Call will be transferred to this contact',
      transfer_options:'Transfer Options',
      primary_extension:'Primary extension',
      voicemail_box:'Voicemail box',

      are_you_ready:'Are you Ready',
      call_transfer_to_conference:'Call will be transferred to this conference',
      contacts_will_be_transfered_to_conference:'ã�“ã‚Œã‚‰ã�®æŽ¥ç‚¹ã�¯ã€�ä¼šè­°å®¤ã�«è»¢é€�ã�•ã‚Œã�¾ã�™',
      Options:'Options',
      add_yourself_to_conference:'Add yourself to the conference',
      join_me_as_well:'Join me as well',
      transfer_to_conference_room:'ä¼šè­°å®¤ã�¸ã�®è»¢é€�',
     search_by_room_or_person:'Search by room or person',
      Call_Later:'å¾Œã�§å‘¼ã�³å‡ºã�—',
      Skip:'ã‚¹ã‚­ãƒƒãƒ—',
 

  },
  
 

  
}
