fjs.i18n = {
	'us':{
    /******global*****/
    contacts:'Contacts',
    Groups:'Groups',
    group: 'group',
    Conferences:'Conferences',
    queues:'Queues',
    member:'member(s)',
    phone:'Phone',
    date:'Date',
    type:'Type',
    Call:'Call',
    chat:'Chat',
    recordings:'Recordings',
    cancel:'cancel',
    select:'Select',
    clear_selection:'Clear Selection',
    
		/****************ME LABELS******************/
		avatar_hover_menu: '写真ホバーメニュー遅延',
		enable_box: 'ボックス有効化',
		reset_app_menu_order: 'アプリメニューオーダーをリセット',
		sound_quality: '音質設定',
		web_phone_state: 'Web phone state',
		registered: 'registered',
		microphone: 'microphone',
		me: 'me',
		all: 'all',
		name: 'name',
		extension: 'extension',
		call_status: 'Call Status',
		hud_status: 'HUD Status',
		available: 'available',
		away:'away',
		busy:'busy',
		favorites: 'favorites',
		external: 'external',
		
    my_department: 'My Department',
		my_department_collaborate: 'Collaborate with your colleagues',
		all_other_departments: 'All Other Departments',
		other_departments: 'Other departments',
		my_teams: 'My Teams',
		teams_managed_by_me:'Teams managed by me',
		shared:'Shared',
		member_of_teams: "I'm a member of these teams",
		others:'Others',
		teams_visible_to_everyone:'Teams visible to everyone',
		//call_status:'呼状態',
		members:'Members',
		custom_status:'Custom Status',
		location: 'location',
		carrier: '通信事業者',
		hud_mobile: 'HUDモバイルソフトフォン',
		hud_web:'HUDWebソフトフォン',
		office:'オフィス',
		chat_status: 'CHAT STATUS',
		place_a_call: 'Place a call',
		phone_number:'Phone number',
		cuurent_call:'通話時間',
		transfer:'transfer',
		conf_room:'Conf Room',
		park:	'Park',
        hold:	'Hold',
        REC:	'REC',
        move:	'Move',
        end:	'End',
        accept: 'Accept',
        decline:'Decline',
        talk:'talk',
        recent_calls:'Recent Calls',
  		time:'Time',
    	today:'Today' , 
    	yesterday:'Yesterday',
    	AM: 'am',
　  		PM:	'pm',
  		from:	'from',
    	you:	'you',
  		to:	'to',
   		duration:	'Duration',
		preferences:	'Preferences',
    	general:	'General',
　　　	  language:	'Language',
        autoclear_search:	'Autoclear search',
        autoclear_after: 'Autoclear after ',
        seconds: '秒',
        avatar_hover_menu_delay:	'Avatar hover menu delay',
        enable_box:	'Enable Box',
        reset_app_menu_order:  'Reset App Menu Order',
		sound_quality_setting: 	'音質設定',
		speaker: 'speaker'　,　　	
      	echo:	'Echo',
      	device:'Device',
      	select_device_to_use:'Select Device to use',
      	wave_mapper:'ウェブ・マッパー',
      	input_devices:	'Input Devices',
        output_devices:	'Output Devices',
        ring_devices:	'リングデバイス',
		weblauncher:	'ウェブランチャー',
		general_settings:'一般設定',
        weblauncher_profile:'ウェッブランチャープロファイル',
　　　 	launch_page_when_answered:'Launch web page only when the call is answered',
		outbound_calls:'Outbound Calls',
		outbound_calls_settings:'Outbound calls settings',
		launch_page_during_calls: '発信時ウェブ表示',
		launch_page_after_hang_up:'切断時ウェブ表示',
		silent:'Silent',
		auto_launch:'Auto Launch',
		inbound_calls:'Inbound Calls',
		inbound_call_settings:'inbound call settings',
		web_launcher_variables:'Web Launcher Variables',
		web_launcher_var_desc:'Web launcher variables description',
		variables:'Variable',
		description:'Description',
		inbound:'インバンド',
		outbound:'アウトバンド',
		wl_var_desc_username_accounts:'認証を要求するアカウントのユーザネーム',
		wl_var_desc_duration:'通話の経過時間（秒）',
		wl_var_desc_name_of_party:'接続先番号',
		wl_var_desc_call_type:'呼種別',
		wl_var_desc_your_ext:'内線番号',
		wl_var_desc_name_of_your_party:'接続先番号',
		wl_var_desc_your_password:'認証を要求するアカウントのパスワード',
		wl_var_desc_caller_number:'%%caller_number%%文字列の削除された部分',
		waiting:'Waiting',
		calls:'calls',
		avg_wait:'Avg Wait',
		avg_talk:'Avg Talk',
		minutes:'minutes',
		abandoned:'Abandoned',
		avatar_upload: '写真 アップロード',
    	first_name:	'First name',
     	last_name:	'Last Name',
    	display_name:'Display Name',
　      email: 'E-Mail',
   		mobile:	'Mobile',
　　    voicemail:	'ボイスメールアドレス',
　　    business_phone:	'Business phone',
　　    IMS:	'IMS',
       JID:	'JID',
	   alerts: 'Alerts',
	   configure_desktop_alerts: 'Configure Desktop Alerts',
	   show_alerts:	'Show alerts',
   	   show_status_when_busy:' Show when status is "Busy"',
   	   show_when_app_in_focus:'Show when app is in focus',
   	   voicemail_alerts:'VOICEMAIL ALERTS',
   	   configure_desktop_alerts:'Configure voicemail desktop alerts',
   	   show_when_new_voicemail: 'Show when new voicemail arrives',
   	   call_alerts: 'Call Alerts',
　     configure_call_desktop_alerts:'通話デスクトップアラート設定',
       incoming_calls:	'Incoming Calls',
       outbound_calls:	'Outgoing Calls',
	   display_for:	'Display for',
　　　　all_my_calls:	'All my calls',
       only_for_known_numbers:	'既知の番号のみ表示する',
       never_display:	'Never display',
       entire_call_recommended: 'Entire Call (recommended)',
       while_phone_is_ringing:' 呼び出し中表示',
       queue_alerts: 'Queue Alerts',
       configure_queue_not_and_desktop_alerts: 'Configure queue notifications and desktop alerts',
       select_all: 'Select All',
       long_waiting_call: 'Long Waiting Calls',
       notifications: 'Notifications',
       desktop_alerts: 'Desktop Alerts',
       abandoned_calls: 'Abandoned Call',
       cp: 'CP',
       HOME: 'HOME',
       user_control_panel:'User Control Panel',
       features: 'Features (FMFM etc.)',
       features_desc_sum:'Many functions can be used via your phone',
       ACD: 'ACD',
       auto_call_distro:'自動通話振り分け',
       about: 'About',
       fonality_web_client:'Fonality Web Client',
       fon_cloud_service:'Fonality Cloud Service',
       custom_message:'Custom Message',
       current_call:'Current Call',
		interface_word:'interface',
		application_tuning:'Application tuning',
		sound_quality:'Sound Quality',
        sound_settings:'Sound Settings',
        sounds: 'Sounds',
        enable_chat_sound:'Enable chat sound',
        on_message_received:'On message received',
        on_sent_message:'On sent message',
       sound_settings_general_desc:'Sound settings for chat and notifications',
       call_preferences:'Call preferences',
       call_log_size:'Call log size',
       busy_ring_back:'Busy ring back',
       auto_away: 'Auto Away',
       auto_away_settings_desc: 'Auto away settings',
       auto_away_after: 'Auto away after',
       enable_auto_away:'Enable Auto away',
       dashboard:'DASHBOARD',
       dashboard_setting: 'Dashboard settings',
       use_column_layout: 'Use column layout',
       web_launcher: 'Web Launcher',
       web_launcher_profile:'Web Launcher Profile',
       web_launcher_on_new_calls:'Launch the web page below during new calls',
       web_launcher_on_hang_ups:'Launcher the web page below after call hangs up',
       queue_summary_stats:'Queue summary stats',
       highlight_threshold:'Highlight threshold. Set to 0 if stat is never highlighted.',
       calls:'Calls',
       waiting:'Waiting',
       my_account:'My account',
       my_account_info:'My account information',
       login:'Login',
       Server:'Server',
       my_personal_info: 'My Personal Information',
       my_personal_info_desc: 'This information is visible to your contacts list',
       avatar:'Avatar',
       reset_alert_position:'Reset Alert Position',
       fon_pbx_control_server: 'Fonality PBX Control Server',
       fon_pbx_server:'Fonality PBX Server',
       fon_plugin:'Fonality Plugin',
       version:'Version',
       fdp_version:'FDP Version',
       hud_server_version:'HUDserver Version',
       fon_core_version:'FONcore Version',
       /***TOP NAVIGATION LABELS **/
       me:'Me',
       call_and_recordings:'Calls and Recordings',
       conferencing:'Conferencing',
       callcenter:'Call Center',
       zoom:'Video Collaboration',
       search:'Search',
       box:'Box',

       /***Left Bar Navigation **/
       all:'All',
       recent:'Recent',
       new_word:'New',
		  loading:'Loading',
      offline:'offline',
      events:'events',
      new_call:'New Call',
      add_someone:'Add Someone',

      /**** ZOOM ****/
      video_collaboration_summary: "You are licensed to use Fonality's Video Collaboration. With this feature, you can hold live video meetings with others inside, or outside, your company. You can even share screens. To get started, simply join or start a meeting below.",
      join_summary:"To join a video collaboration session started by someone else, enter the Meeting ID below, and click the 'Join Now' button.",
	    create_summary:"To create a new video collaboration session, select the type of video session you'd like to start below, and optionally select people from HUD that you'd wish to invite - they will be sent a link in HUD automatically.",
      start_screen_share_only:"Start with Screen Share Only",
      start_with_video:"Start with Video",
      join_now:'Join Now',
      join:'Join',
      create:'Create',
      link:'Link',
      meeting_id:'Meeting ID',
      zoom_created:'Video Meeting has been created',
      link_to_join:'link to join:',
      to:'to',
      from:'from',
      /*****Search WIdget ******/
      type_for_results:'Type or speak for results',
      search_to_start_convo:'Search to Start Conversation',
      type_subject_name:'Type or speak name of contact, team, queue, or conference room...',
    
      /***** Call Recordings *****/
      call_log_tab:'Call Log',
      voicemail_tab:'Voicemails',
      my_recordings_tab:'My Recordings',
      no_transcriptions:'no transcription available',

      action:'Actions',
      mark_all_incoming_vm_read:'Mark all incoming voicemails as read',
      mark_all_incoming_vm_unread:'Mark all incoming voicemails as unread',
      delete_all_incoming_read:'Delete all read incoming voicemails', 

      sort_newest_first:'Newest First',
      sort_alphabetically:'Alphabetically',
      sort_oldest_first:'Oldest First',
      sort_read_status:'Read Status',

      /*****Conferences*******/
      conferencing:'Conferencing',
      conference_member:'Conference Members',
      my_rooms:'My Rooms',
      all_rooms:'All Rooms',
      find_free_room:'Find Free Room & Join',
      sort_room:'Sort By Room Number',
      sort_room_by_location:'Sort By Location',
      sort_by_activity:'Sort By Activity',
      sort_by_room_number:'Sort By Room number',
      conf_summary_my_rooms:'These are the rooms that you have advanced permissions to use, such as adding or removing other users.',
      conf_summary_all_rooms:'You may have limited control over some rooms in this list, such as adding or removing other users',
      free_room:'Free room',
      occupied:'Occupied',
      talking:'talking',
      rooms:'Rooms',
      room:'Room',
      total:'Total',
      you_are_on_call:'you are on a call',
      
      not_a_member_of_conference:'You are not a member of this conference',
      join_to_chat:'Join conference call to use chat.',
      only_see_messages_during_chat:'You can see only messages sent during conference call.',

      leave:'Leave',
      /***Conversation***/
      department:'Department',
      member_of_department:'Contact is a member of this department',
      our_teams:'Our Teams',
      both_in_these_teams:'We are both both in these terms',

      /*****QUEUES******/
      login_all:'Login All',
      logout_all:'Logout All',
      logged_in:'Logged In',
      Logged_out:'Logged Out',
      logout:'Log Out',
      active:'Active',
      queue_name:'Queue Name',
      my_queue:'My Queue',
      all_queues:'All Queues',
      my_status:'My Status',
      agents:'Agents',
      queue_sort_calls_wait:'Calls Waiting',
      queue_sort_avg_wait_time:'Average wait time(ESA)',
      queue_sort_avg_talk_time:'Average talk time',
      queue_sort_total_calls:"Total calls (since last reset)",
      queue_abandoned_calls:'Abandoned calls',
      queue_active_calls:'Active calls',
      agents_logged_into_queue:'Agents logged into the queue',
      agents_logged_out_of_queue:'Agents logged into the queue',


      /******POPUPS*****/
      add_a_new_contact:'Add a New Contact',
      contact_info:'Contact Information',
      want_to_know_who_is_calling:'Want to know who is calling you?',
      messaging:'Messaging',
      want_to_chat_with_this_person:'Want to chat and e-mail this person?',
     
      visibility:'Visibility',
      add_to_favorites:'add to favorites group',
      phones:'Phones',
      add_contact_phone_to_make_calls:'Add contact phone to make calls',
      google_talk:'GoogleTalk (JID)',
      add_contact:'Add Contact',
      save_changes:'Save Changes',


      sign_out:'Sign out',

      Message:'Message',
      message_individual:'This chat message will be sent to each team member individually.',
      Security:'Security',
      visible_to_entire:'Visible to entire company',
      job_is_done:'Job is done?',
      click_to_delete:'Click here to delete this team and say goodbye.',
      create_team:'Create Team',
      send_message:'Send Message',
      delete_group:'Delete Group',
      delete_word:'Delete',
      team_description:'Team description is used for search and provides useful information to the team members.',
      open:'Open',
      old:'Old',
      send:'Send',
      file_share:'File Share',
      sort_by_name:'Sort By Name',
      sort_by_call_status:'Sort By Call Status',
      sort_by_chat_status:'Sort By Chat Status',
      /****Phone Notifications ***/
      clear_all:'Clear All',
      /***page**/
      page:'Page',
      group_page:'Group Page',
      group_intercom:'Group Intercom',
      group_voicemail:'Group Voicemail',
      tab_shows_group_call_members:'this tab shows group call members. No group call at this moment',
      no_active_call:'No active call',

      /****DOCK AREA *****/
      parked_calls:'Parked Calls',
      no_calls_on_park:'no calls on park',

  },

	/*****Japanese Language******/
	'jp':{

    /******global*****/
    contacts:'Contacts',
    Groups:'Groups',
    group: 'グループ',
    Conferences:'Conferences',
    queues:'キュー',
    member:'',
    Call:'呼出',
    chat:'チャット',
    recordings:'録音',
    cancel:'キャンセル',
    select:'選択',
    clear_selection:'選択解除',

		/****************ME LABELS******************/
		avatar_hover_menu: '写真ホバーメニュー遅延',
		enable_box: 'ボックス有効化',
		reset_app_menu_order: 'アプリメニューオーダーをリセット',
		sound_quality: '音質設定',
		web_phone_state: 'ウェブフォン状態',
		registered: '登録ずみ',
		microphone: 'マイクロホン',
		custom_message:'カスタムメッセージ',
		interface_word:'インタフェース',
		application_tuning:'アプリケーションのチューニング',
		me: '自席',
		all: '全席',
		name: '名称',
		extension: '内線',
		call_status: '端末状態',
		hud_status: 'HUD 状態',
		available: 'オンライン/オフライン',
		away:'離席',
		busy:'取り込み中',
		favorites: 'よく使う端末',
		external: '外部コンタクト',
		my_department: '部門',
		my_department_collaborate: '部門のメンバ',
		all_other_departments: '全ての他部門',
		other_departments: '他部門',
		my_teams: 'チーム',
		teams_managed_by_me:'管理チーム',
		shared:'シェアチーム',
		member_of_teams: '私はチームメンバです',
		others:'その他',
		teams_visible_to_everyone:'他に見えるチーム',
		//call_status:'呼状態',
		members:'メンバー',
		custom_status:'マイメッセージ',
		location: 'マイメッセージ',
		carrier: '通信事業者',
		hud_mobile: 'HUDモバイルソフトフォン',
		hud_web:'HUDWebソフトフォン',
		office:'オフィス',
		chat_status: 'チャット状態',
		place_a_call: '発信',
		phone_number:'電話番号',
		cuurent_call:'通話時間',
		transfer:'転送',
		conf_room:'電話会議',
		park:	'パーク',
        hold:	'保留',
        REC:	'録音',
        move:	'ロケーション移動',
        end:	'終了',
        accept: '許容',
        decline:'拒否',
        talk:'　通話中',
        recent_calls:'最近の通話',
  		date:'日',
  		time:'時',
    	today:'今日' , 
    	yesterday:'昨日',
    	AM: '午前',
　  		PM:	'午後',
  		from:	'発信元',
    	you:	'あなた',
  		to:	'通話相手',
   		duration:	'通話時間',
		Preferences:	'HUDWeb情報',
    	general:	'一般',
　　　	language:	'言語',
        autoclear_search:	'自動クリア検索',
        autoclear_after:'自動クリア検索',
        seconds: '秒',
        avatar_hover_menu_delay:	'写真ホバーメニュー遅延',
        enable_box:	'ボックス有効化',
        reset_app_menu_order:  'アプリメニューオーダーをリセット',
        sound_quality:'音質設定',
        sound_settings:'音の設定',
		sound_quality_setting: 	'音質設定',
		speaker: 'スピーカー'　,　　	
      	echo:	'エコー',
      	device:'端末',
      	select_device_to_use:'利用デバイス設定',
      	wave_mapper:'ウェブ・マッパー',
      	input_devices:	'入力デバイス',
        output_devices:	'出力デバイス',
        ring_devices:	'リングデバイス',
		weblauncher:	'ウェブランチャー',
		general_settings:'一般設定',
        weblauncher_profile:'ウェッブランチャープロファイル',
　　　 	launch_page_when_answered:'着信応答時ウェブ表示',
		outbound_calls:'アウトバンドコール',
		outbound_calls_settings:'アウトバンド設定',
		launch_page_during_calls: '発信時ウェブ表示',
		launch_page_after_hang_up:'切断時ウェブ表示',
		silent:'サイレント',
		auto_launch:'自動表示',
		inbound_calls:'インバンドコール',
		inbound_call_settings:'インバンドコール設定',
		web_launcher_variables:'ウェブランチャーパラメータ',
		web_launcher_var_desc:'ウェブランチャーパラメータ記述',
		variables:'パラメータ',
		description:'パラメータ説明',
		inbound:'インバンド',
		outbound:'アウトバンド',
		queues:'またはキュー着信',
		wl_var_desc_username_accounts:'認証を要求するアカウントのユーザネーム',
		wl_var_desc_duration:'通話の経過時間（秒）',
		wl_var_desc_name_of_party:'接続先番号',
		wl_var_desc_call_type:'呼種別',
		wl_var_desc_your_ext:'内線番号',
		wl_var_desc_name_of_your_party:'接続先番号',
		wl_var_desc_your_password:'認証を要求するアカウントのパスワード',
		wl_var_desc_caller_number:'%%caller_number%%文字列の削除された部分',
		waiting:'待ち合わせ中',
		calls:'呼',
		avg_wait:'平均待',
		avg_talk:'平均通話時間',
		minutes:'分',
		abandoned:'途中放棄',
		avatar_upload: '写真 アップロード',
    	first_name:	'名',
     	last_name:	'姓',
    	display_name:'HUDweb表示名称',
　      email: 'eメール',
   		mobile:	'携帯番号',
　　    voicemail:	'ボイスメールアドレス',
　　    business_phone:	'ビジネス番号',
　　    extension:	'内線番号',
       IMS:	'IMS',
       JID:	'JID',
　　　  my_department:'所属部門',
	   alerts: 'アラート',
	   configure_desktop_alerts: 'デスクトップアラート設定',
	   show_alerts:	'アラート表示',
   	   show_status_when_busy:'ビジー時アラート表示',
   	   show_when_app_in_focus:'アプリケーションフォーカス時表示',
   	   voicemail_alerts:'ボイスメールアラート',
   	   configure_desktop_alerts:'デスクトップアラート設定',
   	   show_when_new_voicemail: '新着のボイスメールを表示',
   	   call_alerts: '通話アラート',
　     configure_call_desktop_alerts:'通話デスクトップアラート設定',
   	   type:'タイプ',
       incoming_calls:	'発信通話',
       outbound_calls:	'着信通話',
	   display_for:	'表示条件',
　　　　all_my_calls:	'全ての通話を表示する',
       only_for_known_numbers:	'既知の番号のみ表示する',
       never_display:	'表示しない',
       entire_call_recommended: '常に表示',
       while_phone_is_ringing:' 呼び出し中表示',
       queue_alerts: 'キューアラート',
       configure_queue_not_and_desktop_alerts: 'キュー通知とデスクトップアラート設定',
       select_all: '全て選択',
       long_waiting_call: '長時間待ち合わせ',
       notifications: '通知',
       desktop_alerts: 'デスクトップアラート',
       abandoned_calls: '途中放棄',
       cp: 'ＣＰ画面',
       HOME: 'HOME',
       user_control_panel:'ユーザコントロールパネル',
       features: '機能（FMFM等）',
       ACD: 'ACD',
       auto_call_distro:'自動通話振り分け',
       about: 'Fonality情報',
       fonality_web_client:'フォナリティWEBクライアント',
       fon_cloud_service:'フォナリティクラウドサービス',
       current_call:'通話通の呼',
       sounds: '音',
       sound_settings_general_desc:'チャットと通知のサウンド設定',
       enable_chat_sound:'チャットサウンドをオンにする',
       on_message_received:'メッセージ受信時',
       on_sent_message:'メッセージ送信時',
        call_preferences:'通話の設定',
       call_log_size:'通話ログファイルサイズ',
       busy_ring_back:'ビジーリングバックトーン',
       auto_away: '自動離席',
       auto_away_settings_desc: '自動離席設定',
       auto_away_after: '自動離席後',
       enable_auto_away:'自動離席を有効',
       dashboard:'ダッシュボード',
       dashboard_setting: 'ダッシュボードの設定',
       use_column_layout: '列のレイアウトを使用して',
       web_launcher:'ウェブランチャー',
       web_launcher_profile:'ウェッブランチャープロファイル',
       web_launcher_on_new_calls:'着信時ウェブ表示',
       web_launcher_on_hang_ups:'切断時ウェブ表示',
       queue_summary_stats:'キュー要約統計',
       highlight_threshold:'しきい値を強調表示します。 STATが強調されることはありません場合は、0に設定してください。',
       my_account:'アカウント',
       my_account_info:'アカウント情報',
       login:'ログイン',
       Server:'サーバー',
       my_personal_info: '個人情報',
       my_personal_info_desc: 'この情報は、コンタクトリストに表示されます',
       avatar:'写真',
       reset_alert_position:'アラート位置をリセット',
      features_desc_sum:'電話を使う多くの機能',
      fon_pbx_control_server: 'FONALITYのPBX管理サーバー',
       fon_pbx_server:'FONALITYのPBXサーバー',
       fon_plugin:'FONALITYプラグイン',
       version:'バージョン',
       fdp_version:'FDPのバージョン',
       hud_server_version:'HUDサーバーバージョン',
       fon_core_version:'FONcoreバージョン',
      phone: '電話',    
       me:'自席',
       call_and_recordings:'通話と録音',
       conferencing:'会議中',
       callcenter:'コールセンター',
       zoom:'ビデオ会議',
       search:'検索',
       box:'ボックス',
       /***Left Bar Navigation **/
       all:'全席',
       recent:'最近の',
       new_word: '新しい',
       loading:'ローディング',
       offline:'オフラインで',
       events: 'イベント',
       add_someone:'任意のメンバ追加',

       /**** ZOOM ****/
      video_collaboration_summary: "お客様は弊社の用意するビデオ連携サービスをご利用していただくことができます。本機能は日本国内にある社内外においてビデオ会議を開催することができます。あわせてシェアスクリーン機能もご利用いただけます。",
      join_summary:"ビデオ会議を利用するためにはミーティングＩＤを入力し、'参加する'ボタンをクリックしてください。",
      create_summary:"下記の３つのタイプからビデオセッションを選択し、利用することができます。",
      create:'クリエート',
      start_screen_share_only:"シェアスクリーンのみで開始",
      start_with_video:"video会議開始",
      join_now:'参加する',
      join:'参加',
      meeting_id:'ミーティングＩＤ',
      zoom_created:'ビデオ会議が作成されています',
      link:'リンク',
      link_to_join:'参加するリンク:',
	        
      /*****Search WIdget ******/
      type_for_results:'名称　または番号',
      search_to_start_convo:'会話を始めるために検索する',
      type_subject_name:'コンタクト名称,チーム名称、キュー名称または会議室名称...',
      call_log_tab:'通話履歴',
      voicemail_tab:'ボイスメール',
      my_recordings_tab:'通話録音',
      action:'動作',
      no_transcriptions:'テキスト変換はありません',
      to:'から相手',
      from:'から',

      mark_all_incoming_vm_read:'既読のボイスメールにマークする ',
      mark_all_incoming_vm_unread:'未読のボイスメールにマークする ',
      delete_all_incoming_read:'既読のボイスメールを削除する ', 

      sort_newest_first:'新しい順',
      sort_alphabetically:'アルファベット順 ',
      sort_oldest_first:'古い順',
      sort_read_status:'既読状態',
  
       /*****Conferences*******/
      conferencing:'会議中',
      my_rooms:'個人の会議室',
      all_rooms:'全ての会議室',
      find_free_room:'空き会議室＆参加',
      sort_room:'利用中で並べ替え',
      sort_room_by_location:'ロケーション ',
      sort_by_activity:'利用中',
      sort_by_room_number:'部屋番号で並べ替え',
      conf_summary_my_rooms:'参加指示、退出指示等の拡張権限を利用できる会議室',
      conf_summary_all_rooms:'参加指示、退出指示等の拡張権限が制限されている可能性がある会議室',
      conf_members:'Conference Members',
      free_room:'空室',
      occupied:'利用中',
      talking:'通話中',
      rooms:'部屋数',
      room:'会議室',
      total:'総呼数',
      you_are_on_call:'あなたは電話会議に参加しています',
      not_a_member_of_conference:'あなたはこの電話会議に参加していません。',
      leave:'退出',
      conference_member:'会議メンバ.',
      only_see_messages_during_chat:'会議通話中に送信されたメッセージだけを見ることができます。',
      join_to_chat:'チャットを使用するために電話会議に参加して下さい ',

      /***Conversation***/
      department:'部門',
      member_of_department:'Contact is a member of this department',
      our_teams:'Our Teams',
      both_in_these_teams:'We are both both in these terms',

      /*****QUEUES******/
      login_all:'すべてのログイン',
      logout_all:'すべてログアウト',

      logged_in:'すべてログアウト',
      Logged_out:'Logged Out',
      logout:'ログアウト',
      active:'通話中',
      queue_name:'キュー名称',
      my_queue:'キュー',
      all_queues:'全てのキュー',
      my_status:'状態',
      aban:'放棄呼',
      agents:'内線',

      queue_sort_calls_wait:'待ち呼数 ',
      queue_sort_avg_wait_time:'平均待ち時間 (ESA)',
      queue_sort_avg_talk_time:'平均通話時間 ',
      queue_sort_total_calls:"総呼数 （最後のリセットから）",
      queue_abandoned_calls:'途中放棄呼数 ',
      queue_active_calls:'通話中の呼数 ',
      agents_logged_into_queue:'Agents logged into the queue',
      agents_logged_out_of_queue:'Agents logged into the queue',

      agent_tab:'オペレータ',
      stats_tab:'統計',
      calls_tab:'通話',


      /******POPUPS*****/
      add_a_new_contact:'新しい連絡先を追加',
      messaging:'メッセージ方法',
      want_to_chat_with_this_person:'この人をチャットや電子メールしてみませんか？',
      contact_info:'コンタクト情報',
      want_to_know_who_is_calling:'誰が電話をしてきたのか',

      visibility:'よく見るグループ',
      add_to_favorites:'よく利用するグループへの追加',
      phones:'電話番号',
      add_contact_phone_to_make_calls:'呼び出しを行うために電話を連絡先の追加',
      google_talk:'Googleトーク(JID)',
      add_contact:'連絡先を追加',
      save_changes:'Save Changes',
      agents:'エージェント',
      send:'送信',


      sign_out:'Sign out',

      Message:'セキュリティ',
      message_individual:'This chat message will be sent to each team member individually.',
      Security:'セキュリティ',
      visible_to_entire:'会社全体に表示されます',
      job_is_done:'Job is done?',
      click_to_delete:'Click here to delete this team and say goodbye.',
      create_team:'チームを作成',
      send_message:'Send Message',
      delete_group:'Delete Group',
      delete_word:'Delete',
      team_description:'チームの詳細は検索のために使用されます。',
      open:'開く',
      file_share:'ファイルシェア',

      sort_by_name:'ユーザ名 ',
      sort_by_call_status:'コールステータス ',
      sort_by_chat_status:'チャットステータス ',
   

      /***page ***/
      page:'ページ',
      group_page:'グループページ',
      group_intercom:'グループインターホン ',
      group_voicemail:'グループボイスメール ',
      tab_shows_group_call_members:'このタブにグループコールのメンバーを表示しています。現時点ではグループコールはありません。',
      no_active_call:'通話がありません',

      /****phone notifications ****/
      new_call:'新規通話',
      old:'未読',
      clear_all:'すべてをクリア',

      /****DOCK AREA *****/
      parked_calls:'パーク保留',
      no_calls_on_park:'パーク保留はありません',

      file_share_message:'メッセージ',
      add_message_to_shared:'共有ファイルにメッセージを追加したり、単独でメッセージを送信',
      auto_delete:'自動削除',
      never:'決して',
      hours:'3時間後'
  




  },
  
 

  
}