//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface
 */
fjs.fdp.CallRecordingPlayedEntryModel = function()
{
	
	/**
	 * Call recording status.
	 * @type {String}
	 */
	this.status = null; //$NON-NLS-1$
	/**
	 * Time when call recording was created.
	 * @type {number}
	 */
	this.created = null;
	/**
	 * @type {String}
	 */
	this.originatorPhone = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.callerPhone = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.calleePhone = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.originatorUserId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.callerUserId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.calleeUserId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.queueId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.groupId = null; //$NON-NLS-1$
	/**
	 * @type {boolean}
	 */
	this.incoming = null;
	/**
	 * @type {number}
	 */
	this.duration = null;
	/**
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.conferenceId = null; //$NON-NLS-1$
};
