//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Meta structure provides data about conference call
 * members.
 * @constructor
 */
fjs.fdp.ConferenceMemberEntryModelBase = function()
{
	
	/**
	 * Conference id.
	 * @type {String}
	 */
	this.fdpConferenceId = null; //$NON-NLS-1$
	/**
	 * Display name or caller/callee name on other side or the call
	 * <p/>
	 * In depends on call type, direction, permissions etc. it can be one of the following:
	 * <ul>
	 * <li>Display name of fdp contact</li>
	 * <li>Caller name for external contacts</li>
	 * <li>Conference room name and number (subject for i18n in v1.1)</li>
	 * <li>null/empty - for unknown caller</li>
	 * <li>null/empty - for blocked numbers</li>
	 * </ul>
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * Formatted phone number of person/entity on other side or the call
	 * <p/>
	 * In depends on call type, direction, permissions etc. it can be one of the following:
	 * <ul>
	 * <li>Extension number (3-5 digits) of fdp contact, queue, conference etc.</li>
	 * <li>Formatted external number</li>
	 * <li>Formatted mobile phone number of fdp contact</li>
	 * <li>null/empty - if extension/phone is unknown or blocked by permissions</li>
	 * </ul>
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * In case of office or voicemail call this field provides meta pid (both source id and pid) of contact
	 * on other side of the call. Can be used on client side to get picture of other side of the call.
	 * <br/>
	 * It is empty/null for external calls or in case of applied permissions.
	 * @type {String}
	 */
	this.contactId = null; //$NON-NLS-1$
	/**
	 * This member muted
	 * @type {boolean}
	 */
	this.muted = null;
	/**
	 * Time when member joined conference.
	 * @type {number}
	 */
	this.started = null;
	/**
	 * Member is ringing, i.e. is not yet joined conference
	 * @type {boolean}
	 */
	this.ring = null;
};
