//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * Store all accessTokens with clientType, instance id and protocol version.
 * @constructor
 */
fjs.fdp.FdpAccessTokenEntryModel = function()
{
	
	/**
	 * Username
	 * @type {String}
	 */
	this.username = null; //$NON-NLS-1$
	/**
	 * Node id.
	 * @type {String}
	 */
	this.nodeId = null; //$NON-NLS-1$
	/**
	 * Auth ticket assigned to this user session
	 * @type {String}
	 */
	this.accessToken = null; //$NON-NLS-1$
	/**
	 * Installation identifier (assigned to client on first sync).
	 * @type {String}
	 */
	this.instanceId = null; //$NON-NLS-1$
	/**
	 * Client id (HUDweb, iPhone, Android, etc).
	 * @type {String}
	 */
	this.clientId = null; //$NON-NLS-1$
	/**
	 * Protocol version used for compatibility.
	 * @type {String}
	 */
	this.protocolVersion = null; //$NON-NLS-1$
	/**
	 * Client Iteration used for compatibility.
	 * @type {String}
	 */
	this.iteration = null; //$NON-NLS-1$
	/**
	 * Client build for information purposes.
	 * @type {String}
	 */
	this.build = null; //$NON-NLS-1$
};
