//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Store permanent location of server models for VIP customers.
 */
fjs.fdp.FdpServerRegistryPermanentEntryModel = function()
{
	
	/**
	 * Target server id.
	 * @type {int}
	 */
	this.serverId = null;
	/**
	 * Node id where server model registered.
	 * @type {String}
	 */
	this.nodeId = null; //$NON-NLS-1$
};
