//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Structure for web scenario tests.
 * @constructor
 */
fjs.fdp.FdpTestEntryModelBase = function()
{
	
	/**
	 * Source entry key
	 * @type {String}
	 */
	this.fdpTestKey = null; //$NON-NLS-1$
	/**
	 * Action status:
	 * "done" - if data was injected into feed
	 * "wait" - if server waits for action from client
	 * @type {String}
	 */
	this.status = null; //$NON-NLS-1$
};
