//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface
 */
fjs.fdp.FmfmRuleArgumentEntryModel = function()
{
	
	/**
	 * @type {String}
	 */
	this.pbxFmfmRuleId = null; //$NON-NLS-1$
	/**
	 * @type {int}
	 */
	this.number = null;
	/**
	 * @type {String}
	 */
	this.value = null; //$NON-NLS-1$
};
