//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * List of installed gadgets, collected from settings on client side
 * @constructor
 */
fjs.fdp.GadgetConfigEntryModel = function()
{
	
	/**
	 * Id of context there gadget must be shown
	 * @type {String}
	 */
	this.contextId = null; //$NON-NLS-1$
	/**
	 * Gadget factory id
	 * @type {String}
	 */
	this.factoryId = null; //$NON-NLS-1$
	/**
	 * Entity id (contact, group, etc)
	 * @type {String}
	 */
	this.entityId = null; //$NON-NLS-1$
	/**
	 * Index in the gadgets order
	 * @type {int}
	 */
	this.index = null;
	/**
	 * Gadget config
	 * @type {Object}
	 */
	this.config = null;
};
