//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Meta contact is the structure provided data about groups.
 * Any count of data from different
 * user lists can be joined and use same
 * set of fields.
 */
fjs.fdp.GroupEntryModel = function()
{
	
	/**
	 * Group name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * Server MetaPid
	 * @type {String}
	 */
	this.serverNumber = null; //$NON-NLS-1$
	/**
	 * Group description (empty for v1.0)
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
	/**
	 * Extension
	 * @type {String}
	 */
	this.extension = null; //$NON-NLS-1$
	/**
	 * Group type.
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * Group owner contact id.
	 * @type {String}
	 */
	this.ownerId = null; //$NON-NLS-1$
	/**
	 * Group number
	 * @type {String}
	 */
	this.grouppermissions_groupNumber = null; //$NON-NLS-1$
	/**
	 * Permanent permissions(view/kick).
	 * Bit set of disallowed actions. If zero, all actions allowed.
	 * @type {int}
	 */
	this.grouppermissions_permissions = null;
	/**
	 * XMPP status (available, away, offline)
	 * @type {String}
	 */
	this.groupstatus_chatStatus = null; //$NON-NLS-1$
	/**
	 * Call status (queue, external, office, none)
	 * @type {String}
	 */
	this.groupstatus_callStatus = null; //$NON-NLS-1$
	/**
	 * If true the my contact is member.
	 * @type {boolean}
	 */
	this.groupstatus_meStatus = null;
	/**
	 * Group call creator xpid.
	 * @type {String}
	 */
	this.groupstatus_callCreatedBy = null; //$NON-NLS-1$
	/**
	 * Number of online (not offline) contacts in group.
	 * @type {int}
	 */
	this.groupstatus_online = null;
	/**
	 * Number of away contacts in group.
	 * @type {int}
	 */
	this.groupstatus_away = null;
	/**
	 * Number of all contacts in group.
	 * @type {int}
	 */
	this.groupstatus_contacts = null;
	/**
	 * Number of talking contacts in group.
	 * @type {int}
	 */
	this.groupstatus_talking = null;
};
