//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Meta contact is the structure provided links between
 * contacts and groups.
 */
fjs.fdp.GroupContactEntryModel = function()
{
	
	/**
	 * Group pid
	 * @type {String}
	 */
	this.groupId = null; //$NON-NLS-1$
	/**
	 * Contact pid
	 * @type {String}
	 */
	this.contactId = null; //$NON-NLS-1$
	/**
	 * Group member's list of roles
	 * @type {String}
	 */
	this.role = null; //$NON-NLS-1$
};
