//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Meta structure provides the list of supported languages.
 * @constructor
 */
fjs.fdp.I18nLangEntryModelBase = function()
{
	
	/**
	 * language code
	 * @type {String}
	 */
	this.code = null; //$NON-NLS-1$
	/**
	 * language name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
};
