//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Provides user client with list of known locations.
 */
fjs.fdp.LocationEntryModel = function()
{
	
	/**
	 * Formatted phone or extension associated with this
	 * location.
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * Location full name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * Location short name
	 * @type {String}
	 */
	this.shortName = null; //$NON-NLS-1$
	/**
	 * Location type.
	 * @type {String}
	 */
	this.locationType = null; //$NON-NLS-1$
	/**
	 * Status of current contact device(registered,
	 * unregistered, lagged)
	 * @type {String}
	 */
	this.location_status_deviceStatus = null; //$NON-NLS-1$
	/**
	 * If auto answer supported by location device. True for supported models of hardphones(Aastra, Polycom, Grandstream).
	 * @type {boolean}
	 */
	this.location_status_autoAnswer = null;
};
