//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Meta structure provides runtime status of my contact.
 */
fjs.fdp.MeEntryModel = function()
{
	
	/**
	 * Key of my runtime status property. See
	 * com.fonality.fdp.FDPMyProperty enum for possible values
	 * @type {String}
	 */
	this.propertyKey = null; //$NON-NLS-1$
	/**
	 * Value of my property
	 * @type {String}
	 */
	this.propertyValue = null; //$NON-NLS-1$
};
