//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Provide information about feeds
 * @constructor
 */
fjs.fdp.MetaEntryModelBase = function()
{
	
	/**
	 * @type {String}
	 */
	this.feedId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * Timestamp
	 * @type {int}
	 */
	this.apiVer = null;
	/**
	 * @type {String}
	 */
	this.slices = null; //$NON-NLS-1$
};
