//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Provides information about parked calls.
 */
fjs.fdp.ParkedCallEntryModel = function()
{
	
	/**
	 * Caller Name
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * Caller formatted phone number
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * Call is parked on specified extension and you call take
	 * this call by calling this extension
	 * @type {String}
	 */
	this.parkExt = null; //$NON-NLS-1$
	/**
	 * Call is parked by this contact
	 * @type {String}
	 */
	this.parkerContactId = null; //$NON-NLS-1$
	/**
	 * Caller contact id
	 * @type {String}
	 */
	this.callerContactId = null; //$NON-NLS-1$
	/**
	 * Recipient contact id
	 * @type {String}
	 */
	this.recipientContactId = null; //$NON-NLS-1$
	/**
	 * Recipient display name
	 * @type {String}
	 */
	this.recipientDisplayName = null; //$NON-NLS-1$
	/**
	 * Formatted recipient phone number
	 * @type {String}
	 */
	this.recipientPhone = null; //$NON-NLS-1$
	/**
	 * Creation time
	 * @type {number}
	 */
	this.created = null;
};
