//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface
 */
fjs.fdp.PbxAreaCodeEntryModel = function()
{
	
	/**
	 * Area code
	 * @type {int}
	 */
	this.areacode = null;
	/**
	 * Country
	 * @type {String}
	 */
	this.country = null; //$NON-NLS-1$
	/**
	 * State name
	 * @type {String}
	 */
	this.state = null; //$NON-NLS-1$
	/**
	 * Timezone name
	 * @type {String}
	 */
	this.timezone = null; //$NON-NLS-1$
};
