//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @constructor
 */
fjs.fdp.PbxConferenceEntryModel = function()
{
	
	/**
	 * Extension number
	 * @type {String}
	 */
	this.extensionNumber = null; //$NON-NLS-1$
	/**
	 * Room name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * Room accessibilitry type
	 * @type {String}
	 */
	this.roomType = null; //$NON-NLS-1$
};
