//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface SIP Device is the phone
 */
fjs.fdp.PbxDeviceEntryModel = function()
{
	
	/**
	 * SIP Device name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * SIP Device password
	 * @type {String}
	 */
	this.password = null; //$NON-NLS-1$
	/**
	 * Description of SIP device.
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
	/**
	 * Device type (vendor info)
	 * @type {String}
	 */
	this.deviceType = null; //$NON-NLS-1$
	/**
	 * Location name
	 * @type {number}
	 */
	this.created = null;
	/**
	 * If true device is not provisioned by Fonality.
	 * @type {boolean}
	 */
	this.remotelyProvisioned = null;
	/**
	 * Side Car options.
	 * TODO: The field is not imported because sidecar feature is undefined
	 * yet.
	 * @type {String}
	 */
	this.sidecar = null; //$NON-NLS-1$
	/**
	 * Firmware description and version
	 * @type {String}
	 */
	this.firmware = null; //$NON-NLS-1$
	/**
	 * SQL id of parent device.
	 * TODO Remove this field (unused and not imported).
	 * @type {String}
	 */
	this.parentDeviceId = null; //$NON-NLS-1$
};
