//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface <p>
 * A telephone extension is an internal telephone line attached to a
 * Private branch exchange (PBX).
 * The PBX operates much as a community switchboard
 * does for a geographic telephone numbering plan and allows multiple lines inside
 * the office to connect without each phone requiring a separate outside line.
 * In these systems, a dialer usually has to dial a number (typically 9)
 * to tell the PBX to connect with a landline (also called DDCO)
 * to dial an external number. Within the PBX, the user merely dials the
 * extension number of the person.
 * Each phone line may be extended up to a fixed maximum.
 * </p>
 * <a href="http://en.wikipedia.org/wiki/Extension_(telephone)">wiki</a>
 */
fjs.fdp.PbxExtensionEntryModel = function()
{
	
	/**
	 * @type {String}
	 */
	this.extension = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.ownerUserId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.deviceId = null; //$NON-NLS-1$
	/**
	 * Location name, i.e. 'Main office'
	 * @type {String}
	 */
	this.locationName = null; //$NON-NLS-1$
};
