//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * @constructor
 */
fjs.fdp.PbxFmfmRuleEntryModelBase = function()
{
	
	/**
	 * @type {int}
	 */
	this.step = null;
	/**
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.action = null; //$NON-NLS-1$
};
