//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @constructor
 */
fjs.fdp.PbxFmfmWhitelistEntryModel = function()
{
	
	/**
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.phoneType = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.vip = null; //$NON-NLS-1$
};
