//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @constructor
 */
fjs.fdp.PbxFmfmSettingEntryModel = function()
{
	
	/**
	 * @type {String}
	 */
	this.username = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.find = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.offline = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.online = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.away = null; //$NON-NLS-1$
	/**
	 * @type {int}
	 */
	this.findbusy = null;
	/**
	 * @type {int}
	 */
	this.rejectnocid = null;
	/**
	 * @type {String}
	 */
	this.schedulerId = null; //$NON-NLS-1$
};
