//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * PBX group contains users, extensions, queues, etc. In HUD
 * can be represented as contacts group.
 * @constructor
 */
fjs.fdp.PbxGroupEntryModelBase = function()
{
	
	/**
	 * Group name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * Foreign key to extension related to this group. Groups
	 * having extension ids can be used as conferences
	 * (under some
	 * restrictions).
	 * @type {String}
	 */
	this.pbxExtensionId = null; //$NON-NLS-1$
	/**
	 * Group description.
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
};
