//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface PBX Queue Member
 */
fjs.fdp.PbxQueueMemberEntryModel = function()
{
	
	/**
	 * Queue name
	 * @type {String}
	 */
	this.queueId = null; //$NON-NLS-1$
	/**
	 * Queue item id.
	 * @type {String}
	 */
	this.queuePid = null; //$NON-NLS-1$
	/**
	 * Queue name + extension.
	 * @type {String}
	 */
	this.pbxQueueMemberKey = null; //$NON-NLS-1$
	/**
	 * Identifier of agent in queue.
	 * @type {String}
	 */
	this.extension = null; //$NON-NLS-1$
	/**
	 * Original agent location from asterisk config.
	 * @type {String}
	 */
	this.originalLocation = null; //$NON-NLS-1$
	/**
	 * Indicates permanently logged queue member
	 * @type {boolean}
	 */
	this.permanent = null;
};
