//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * pbx_queue_logout_reason structure provides possible agent absence reasons.
 * @constructor
 */
fjs.fdp.PbxQueueLogoutReasonEntryModelBase = function()
{
	
	/**
	 * Agent absence reason (meaningful primary key)
	 * @type {String}
	 */
	this.reason = null; //$NON-NLS-1$
};
