//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface
 */
fjs.fdp.PbxServerEntryModel = function()
{
	
	/**
	 * Customer id as imported from Fonality Primary Database
	 * @type {String}
	 */
	this.customerId = null; //$NON-NLS-1$
	/**
	 * Server name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.etlSource = null; //$NON-NLS-1$
	/**
	 * CP version
	 * @type {String}
	 */
	this.cpVersion = null; //$NON-NLS-1$
};
