//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface (imported from pbxtra.user_ext_thirdparty_credentials)
 */
fjs.fdp.PbxThirdpartyCredentialsEntryModel = function()
{
	
	/**
	 * @type {String}
	 */
	this.accountId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.vendor = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.service = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.login = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.password = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.options = null; //$NON-NLS-1$
};
