//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * User location structure provides information about user
 * locations.
 * It is not mapped to sql tables directly but can be retrieved
 * by user extensions and mobile phone.
 * @constructor
 */
fjs.fdp.PbxUserLocationEntryModelBase = function()
{
	
	/**
	 * Extension's server id.
	 * @type {int}
	 */
	this.serverId = null;
	/**
	 * Location type 'office' = 0, 'mobile' = 1
	 * @type {int}
	 */
	this.locationType = null;
	/**
	 * Extension number or mobile phone
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * Link to device table
	 * @type {String}
	 */
	this.deviceId = null; //$NON-NLS-1$
	/**
	 * Location name, i.e. 'Main office'
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
};
