//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Voice mail message transcription (text).
 * @constructor
 */
fjs.fdp.PbxVoicemailTranscriptionEntryModelBase = function()
{
	
	/**
	 * @type {String}
	 */
	this.mailbox = null; //$NON-NLS-1$
	/**
	 * Synthetic VM message id from asterisk.
	 * @type {String}
	 */
	this.voicemailMessageKey = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.message = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.recordDate = null; //$NON-NLS-1$
	/**
	 * @type {int}
	 */
	this.duration = null;
	/**
	 * @type {String}
	 */
	this.callerName = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.callerNumber = null; //$NON-NLS-1$
};
