//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * @constructor
 */
fjs.fdp.PermissionPackRightEntryModelBase = function()
{
	
	/**
	 * Permission is assinged to this group id
	 * @type {String}
	 */
	this.permissionGroupId = null; //$NON-NLS-1$
	/**
	 * Permission code
	 * @type {String}
	 */
	this.permission = null; //$NON-NLS-1$
};
