//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface
 */
fjs.fdp.PermissionGroupToPackEntryModel = function()
{
	
	/**
	 * Specify group having permissions to group specified by child_permission_group_id
	 * @type {String}
	 */
	this.permissionGroupId = null; //$NON-NLS-1$
	/**
	 * Specify group having permissions to
	 * @type {String}
	 */
	this.childPermissionGroupId = null; //$NON-NLS-1$
};
