//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Queue messages (broadcasts)
 * @constructor
 */
fjs.fdp.QueueMessageEntryModelBase = function()
{
	
	/**
	 * Queue id
	 * @type {String}
	 */
	this.queueId = null; //$NON-NLS-1$
	/**
	 * Message sender
	 * @type {String}
	 */
	this.sender = null; //$NON-NLS-1$
	/**
	 * Message in plain text.
	 * @type {String}
	 */
	this.message = null; //$NON-NLS-1$
	/**
	 * Message in XHTML.
	 * @type {String}
	 */
	this.messageXhtml = null; //$NON-NLS-1$
	/**
	 * Message received timestamp (PBX).
	 * @type {number}
	 */
	this.time = null;
	/**
	 * Client message id.
	 * @type {number}
	 */
	this.clientId = null;
};
