//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Meta structure provides list of logout reasons for queue.
 * @constructor
 */
fjs.fdp.QueueLogoutReasonEntryModelBase = function()
{
	
	/**
	 * Logout reason key.
	 * @type {String}
	 */
	this.key = null; //$NON-NLS-1$
	/**
	 * Logout reason name.
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
};
