//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Provides user client with list of calls waiting for answer in a queue.
 * @constructor
 */
fjs.fdp.QueueCallEntryModelBase = function()
{
	
	/**
	 * Agent contact id
	 * @type {String}
	 */
	this.agentContactId = null; //$NON-NLS-1$
	/**
	 * Queue.
	 * @type {String}
	 */
	this.queueId = null; //$NON-NLS-1$
	/**
	 * Queue member, who took a call.
	 * @type {String}
	 */
	this.queueMemberId = null; //$NON-NLS-1$
	/**
	 * Display name or a person waiting in a queue.
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * Formatted phone number of person waiting in a queue.
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * In case of somebody from office call to a queue this field contains his id.
	 * In general case only external calls will call to a queue, so this field should be empty.
	 * @type {String}
	 */
	this.contactId = null; //$NON-NLS-1$
	/**
	 * Creation time
	 * @type {number}
	 */
	this.startedAt = null;
	/**
	 * True if call was taken by agent.
	 * @type {boolean}
	 */
	this.taken = null;
	/**
	 * Bit set of disallowed actions. If zero, all actions allowed.
	 * @type {int}
	 */
	this.permissions = null;
	/**
	 * If true this side of call is being recorded.In depends on
	 * permissions this fact can be hidden and value will be always false.
	 * @type {boolean}
	 */
	this.recorded = null;
	/**
	 * If not None this call is barge call
	 * @type {String}
	 */
	this.barge = null; //$NON-NLS-1$
	/**
	 * If not None call is barged by user
	 * @type {String}
	 */
	this.bargedByMeOptions = null; //$NON-NLS-1$
};
