//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface
 */
fjs.fdp.QuickInboxMissedCallEntryModel = function()
{
	
	/**
	 * key
	 * @type {String}
	 */
	this.missedCallKey = null; //$NON-NLS-1$
	/**
	 * Caller if known
	 * @type {String}
	 */
	this.senderId = null; //$NON-NLS-1$
	/**
	 * Caller display name
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * @type {number}
	 */
	this.flag = null;
	/**
	 * @type {String}
	 */
	this.helperUlr = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.iconUrl = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.message = null; //$NON-NLS-1$
	/**
	 * Caller phone number
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * @type {number}
	 */
	this.time = null;
	/**
	 * @type {String}
	 */
	this.title = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * Owner's status when event was created
	 * @type {String}
	 */
	this.receivedStatus = null; //$NON-NLS-1$
	/**
	 * Queue id if this is queue call
	 * @type {String}
	 */
	this.queueId = null; //$NON-NLS-1$
	/**
	 * Conference id if this is conference call
	 * @type {String}
	 */
	this.conferenceId = null; //$NON-NLS-1$
};
