//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @constructor
 */
fjs.fdp.QuickInboxEntryModel = function()
{
	
	/**
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.senderId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.queueId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.vmId = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.title = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.message = null; //$NON-NLS-1$
	/**
	 * @type {number}
	 */
	this.time = null;
	/**
	 * @type {number}
	 */
	this.flag = null;
	/**
	 * @type {String}
	 */
	this.helperUlr = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.iconUrl = null; //$NON-NLS-1$
	/**
	 * Owner's status when event was created
	 * @type {String}
	 */
	this.receivedStatus = null; //$NON-NLS-1$
	/**
	 * Stream event context.
	 * @type {String}
	 */
	this.context = null; //$NON-NLS-1$
	/**
	 * Stream event audience
	 * @type {String}
	 */
	this.audience = null; //$NON-NLS-1$
	/**
	 * JSon data
	 * @type {Object}
	 */
	this.data = null;
};
