//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Store last 30 transfers.
 * @constructor
 */
fjs.fdp.RecentTransfersEntryModelBase = function()
{
	
	/**
	 * Contact id to transfer
	 * @type {String}
	 */
	this.toContactId = null; //$NON-NLS-1$
	/**
	 * Contact id from transfer
	 * @type {String}
	 */
	this.fromContactId = null; //$NON-NLS-1$
	/**
	 * Contact's display name.
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * The timestamp of transfer.
	 * @type {number}
	 */
	this.timestamp = null;
	/**
	 * Mobile phone number.
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
};
