//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Store last chats for recent talks feed.
 */
fjs.fdp.RecentTalkChat35EntryModel = function()
{
	
	/**
	 * Target in jkey form (contact, external phone, conversation (future))
	 * @type {String}
	 */
	this.target = null; //$NON-NLS-1$
	/**
	 * Target's display name.
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * Phone number of external phone for calls, extension number for chats.
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * The timestamp of talk.
	 * @type {number}
	 */
	this.time = null;
};
