//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Recent contacts (known and unknown).
 * @constructor
 */
fjs.fdp.RecentContactEntryModelBase = function()
{
	
	/**
	 * Contact display name.
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
};
