//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Store last 5 chat messages.
 */
fjs.fdp.RecentChatStatusMessagesEntryModel = function()
{
	
	/**
	 * Contact status message
	 * @type {String}
	 */
	this.message = null; //$NON-NLS-1$
	/**
	 * The timestamp of transfer.
	 * @type {number}
	 */
	this.lastUsage = null;
};
