//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Store credentials for login to oauth resource_service.
 * @constructor
 */
fjs.fdp.ResourceServiceEntryModelBase = function()
{
	
	/**
	 * Unique service identifier. Actually service type ("fdp", "pbx", etc.)
	 * @type {String}
	 */
	this.serviceName = null; //$NON-NLS-1$
	/**
	 * Service password
	 * @type {String}
	 */
	this.servicePassword = null; //$NON-NLS-1$
};
