//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * ...
 * @constructor
 */
fjs.fdp.SecurityReportEntryModel = function()
{
	
	/**
	 * Username
	 * @type {String}
	 */
	this.who = null; //$NON-NLS-1$
	/**
	 * Type of attack.
	 * @type {String}
	 */
	this.kindOfAttack = null; //$NON-NLS-1$
	/**
	 * Attack description.
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
	/**
	 * Number of attack attempts.
	 * @type {number}
	 */
	this.attempts = null;
};
