//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * Provides information about wall events
 * @constructor
 */
fjs.fdp.StreamEventWallBaseEntryModel = function()
{
	
	/**
	 * PID of user who	owns this message.
	 * @type {String}
	 */
	this.ownerUserId = null; //$NON-NLS-1$
	/**
	 * User who sent this message.
	 * @type {String}
	 */
	this.senderId = null; //$NON-NLS-1$
	/**
	 * Event audience
	 * @type {String}
	 */
	this.audience = null; //$NON-NLS-1$
	/**
	 * Audience target id
	 * @type {String}
	 */
	this.targetId = null; //$NON-NLS-1$
	/**
	 * Event type
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * Plain text
	 * @type {String}
	 */
	this.message = null; //$NON-NLS-1$
	/**
	 * Event specific data
	 * @type {Object}
	 */
	this.data = null;
	/**
	 * Optional feed_key of replied event
	 * @type {String}
	 */
	this.replyTo = null; //$NON-NLS-1$
	/**
	 * Time when event was created
	 * @type {number}
	 */
	this.created = null;
	/**
	 * Event lifetime, ms. 0 to archive manually.
	 * @type {number}
	 */
	this.archive = null;
	/**
	 * List of members, who was target of event when event received.
	 * @type {String}
	 */
	this.members = null; //$NON-NLS-1$
};
