//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Provides information about events on my server
 * @constructor
 */
fjs.fdp.StreamEventEntryModelBase = function()
{
	
	/**
	 * Entity or contact who sent event.
	 * @type {String}
	 */
	this.from = null; //$NON-NLS-1$
	/**
	 * Event sent to this entity or contact.
	 * @type {String}
	 */
	this.to = null; //$NON-NLS-1$
	/**
	 * Event sent in the context of this entity or contact. If
	 * not specified - means same value as field to.
	 * @type {String}
	 */
	this.context = null; //$NON-NLS-1$
	/**
	 * Event type.
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * Plain text.
	 * @type {String}
	 */
	this.message = null; //$NON-NLS-1$
	/**
	 * Timestamp of event creation.
	 * @type {number}
	 */
	this.created = null;
	/**
	 * Timestamp of event modification. undefined means same
	 * value as create field.
	 * @type {number}
	 */
	this.modified = null;
	/**
	 * Event still in action or completed.
	 * @type {String}
	 */
	this.state = null; //$NON-NLS-1$
	/**
	 * Event type specific value, can be used to join few events
	 * into one.
	 * @type {String}
	 */
	this.link = null; //$NON-NLS-1$
	/**
	 * id of replied event
	 * @type {String}
	 */
	this.replyTo = null; //$NON-NLS-1$
	/**
	 * Event specific data.
	 * @type {Object}
	 */
	this.data = null;
};
