//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * Structure for unit testing purposes. It has relaxed construction requirements (public
 * factory com.fonality.hdb.test.structure.TestStructureFactory2).
 * @constructor
 */
fjs.fdp.TestStructureEntryModelBase = function()
{
	
	/**
	 * Test string value.
	 * @type {String}
	 */
	this.text = null; //$NON-NLS-1$
	/**
	 * Test integer value.
	 * @type {int}
	 */
	this.index = null;
};
