//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface Meta contact is the structure provided data about time difference between client and server.
 */
fjs.fdp.TimeEntryModel = function()
{
	
	/**
	 * Timestamp key.
	 * @type {String}
	 */
	this.tsKey = null; //$NON-NLS-1$
	/**
	 * Timestamp value.
	 * @type {number}
	 */
	this.tsValue = null;
};
