//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @constructor
 */
fjs.fdp.UseractivityEntryModel = function()
{
	
	/**
	 * Activity key. Any value is possible and defined by client
	 * logic.
	 * @type {String}
	 */
	this.key = null; //$NON-NLS-1$
	/**
	 * Activity's value. Any value is possible and defined by
	 * client logic.
	 * @type {number}
	 */
	this.value = null;
};
