//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * Provides voicemail box contents.
 * Any count of data from different user lists can be joined and use same set of fields.
 * @constructor
 */
fjs.fdp.VoicemailMessageEntryModel = function()
{
	
	/**
	 * Synthetic VM message id from asterisk
	 * @type {String}
	 */
	this.voicemailMessageKey = null; //$NON-NLS-1$
	/**
	 * Caller name
	 * @type {String}
	 */
	this.displayName = null; //$NON-NLS-1$
	/**
	 * Caller address
	 * @type {String}
	 */
	this.phone = null; //$NON-NLS-1$
	/**
	 * Id of contact if it is voicemail from contact.
	 * @type {String}
	 */
	this.contactId = null; //$NON-NLS-1$
	/**
	 * Message duration in milliseconds
	 * @type {number}
	 */
	this.duration = null;
	/**
	 * Message date
	 * @type {number}
	 */
	this.date = null;
	/**
	 * If true - message is read.
	 * @type {boolean}
	 */
	this.readStatus = null;
	/**
	 * Message flag
	 * @type {int}
	 */
	this.flag = null;
	/**
	 * Recognized text of voicemail message.
	 * @type {String}
	 */
	this.transcription = null; //$NON-NLS-1$
};
