//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface fdp_weblauncher_variable is the structure provided data
 * about web launcher variables
 */
fjs.fdp.WebLauncherVariablesEntryModel = function()
{
	
	/**
	 * Unique variable name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * Variable description
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
};
