//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * This meta structure provided tasks(url) to launch on client side.
 * @constructor
 */
fjs.fdp.WebLauncherTaskEntryModel = function()
{
	
	/**
	 * @type {String}
	 */
	this.key = null; //$NON-NLS-1$
	/**
	 * @type {String}
	 */
	this.url = null; //$NON-NLS-1$
	/**
	 * Hangup url flag
	 * @type {boolean}
	 */
	this.typeHangup = null;
	/**
	 * Silent mode flag
	 * @type {boolean}
	 */
	this.silent = null;
};
