//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntryBase
 * xef0010_reflex_variable is the structure provided data
 * about web launcher variables
 * @constructor
 */
fjs.fdp.Xef0010ReflexVariableEntryModelBase = function()
{
	
	/**
	 * Unique variable name
	 * @type {String}
	 */
	this.xef0010ReflexVariableName = null; //$NON-NLS-1$
	/**
	 * Variable description
	 * @type {String}
	 */
	this.xef0010ReflexVariableDescription = null; //$NON-NLS-1$
};
