//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * xef0010_reflex is the structure provided data about web
 * launchers, app launchers, etc.
 * @constructor
 */
fjs.fdp.Xef0010ReflexEntryModel = function()
{
	
	/**
	 * Id
	 * @type {String}
	 */
	this.confId = null; //$NON-NLS-1$
	/**
	 * Web launcher name
	 * @type {String}
	 */
	this.name = null; //$NON-NLS-1$
	/**
	 * Web launcher description
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
	/**
	 * Sets this launcher enabled by default
	 * @type {boolean}
	 */
	this.enabledByDefault = null;
	/**
	 * Launch web page only when the call is answered
	 * @type {boolean}
	 */
	this.launchOnlyWhenAnswered = null;
	/**
	 * name of external account to use with this action.
	 * predefined account types are starts with "fonality:". "fonality:hud",
	 * "conality:cp", if empty HUD must use locally specified account (like
	 * in HUD 3.5)
	 * @type {String}
	 */
	this.accountType = null; //$NON-NLS-1$
};
