//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * xef0007_vcard_picture_external_base structure provides
 * vCard pictures for external contacts.
 * @constructor
 */
fjs.fdp.Xef0007VcardPictureExternalBaseEntryModel = function()
{
	
	/**
	 * Owner server id
	 * @type {int}
	 */
	this.serverId = null;
	/**
	 * sha1 hash of picture, same hash should be in presence
	 * @type {String}
	 */
	this.pictureId = null; //$NON-NLS-1$
	/**
	 * jid
	 * @type {String}
	 */
	this.jid = null; //$NON-NLS-1$
	/**
	 * vCard's pictures
	 * @type {byte[]}
	 */
	this.picture = null;
	/**
	 * picture's type (image/png, image/jpeg, etc)
	 * @type {String}
	 */
	this.pictureType = null; //$NON-NLS-1$
};
