//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * xef0010_reflexes is the structure provided data about web
 * launchers, app launchers,
 * etc.
 * @constructor
 */
fjs.fdp.Xef0010ReflexActionEntryModel = function()
{
	
	/**
	 * Reflex id
	 * @type {String}
	 */
	this.xef0010ReflexId = null; //$NON-NLS-1$
	/**
	 * Url type (on inbound, inbound.hangup, outbound or
	 * outbound.hangup)
	 * @type {String}
	 */
	this.type = null; //$NON-NLS-1$
	/**
	 * Url href
	 * @type {String}
	 */
	this.url = null; //$NON-NLS-1$
	/**
	 * Url description
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
	/**
	 * Launch a web page in silent mode
	 * @type {boolean}
	 */
	this.silent = null;
	/**
	 * Launch a web page manually (if value = false) or
	 * automatically (if value = true)
	 * @type {boolean}
	 */
	this.autoLaunch = null;
};
