//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * @interface XMPP contact is the external contact as defined by HUD user.
 */
fjs.fdp.XmppContactBaseEntryModel = function()
{
	
	/**
	 * Owner server id
	 * @type {int}
	 */
	this.serverId = null;
	/**
	 * Contact owner
	 * @type {String}
	 */
	this.ownerUserId = null; //$NON-NLS-1$
	/**
	 * Contact nick name
	 * @type {String}
	 */
	this.nickName = null; //$NON-NLS-1$
	/**
	 * Jabber/XMPP identifier.
	 * @type {String}
	 */
	this.jid = null; //$NON-NLS-1$
	/**
	 * Subscription state
	 * @type {String}
	 */
	this.subscriptionState = null; //$NON-NLS-1$
	/**
	 * Contact description.
	 * @type {String}
	 */
	this.description = null; //$NON-NLS-1$
	/**
	 * Contact's direct phone number
	 * @type {String}
	 */
	this.directPhone = null; //$NON-NLS-1$
	/**
	 * Contact's e-mail address
	 * @type {String}
	 */
	this.email = null; //$NON-NLS-1$
	/**
	 * Contact's first name
	 * @type {String}
	 */
	this.firstName = null; //$NON-NLS-1$
	/**
	 * Contact's last name
	 * @type {String}
	 */
	this.lastName = null; //$NON-NLS-1$
	/**
	 * Contact's full name
	 * @type {String}
	 */
	this.fullName = null; //$NON-NLS-1$
	/**
	 * Semicolon separated list of user Im's
	 * @type {String}
	 */
	this.ims = null; //$NON-NLS-1$
	/**
	 * Contact's mobile number
	 * @type {String}
	 */
	this.mobile = null; //$NON-NLS-1$
};
