//{FON:GEN:d6dc6cae606675f2e4fc6aad891c41b3} GENERATED CODE! DO NOT EDIT MANUALY!
namespace('fjs.fdp');


/**
 * Code generated by com.fonality.meta.generator.java.fdp.client.fjs.JGen_FJS_FeedModelEntry
 * Mapping User2Group
 * @constructor
 */
fjs.fdp.XmppUser2groupEntryModel = function()
{
	
	/**
	 * User JID
	 * @type {String}
	 */
	this.contactJid = null; //$NON-NLS-1$
	/**
	 * Group Id source. See MetaSourceId
	 * @type {number}
	 */
	this.groupIdSource = null;
	/**
	 * Group id as defined in pbx or xmpp roster
	 * @type {String}
	 */
	this.groupId = null; //$NON-NLS-1$
};
